act_code: '19611'
requisite: Решение Маслихата города Астаны от 30 марта 2004 года № 28/6-III. Зарегистрировано Департаментом юстиции города Астаны 5 мая 2004 года № 326. Утратило силу решением маслихата города Астаны от 20 июля 2017 года № 166/21-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О правилах благоустройства, санитарного содержания, организации уборки и обеспечения чистоты на территории города Астаны
  kaz: Аббатандыру, санитарлық жабдықтау, жинау жұмыстарын ұйымдастыру және Астана қаласының аумағында тазалықты қамтамасыз ету қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-03-29
approved_by:
- '151000000002'
version_date:
  kaz: 2009-11-06
  rus: 2009-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/19611/kaz/06.11.2009
  rus: https://zan.gov.kz/client/#!/doc/19611/rus/06.11.2009
caused_by:
  code: '49378'
  requisite: Решение маслихата города Астаны от 6 ноября 2009 года N 271/39-IV. Зарегистрировано Департаментом юстиции города Астаны 15 декабря 2009 года N 602. Утратило силу решением маслихата города Астаны от 20 июля 2017 года № 166/21-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 30 марта 2004 года № 28/6-III "О правилах благоустройства, санитарного содержания, организации уборки и обеспечения чистоты на территории города Астаны"
    kaz: Астана қаласы мәслихатының 2004 жылғы 30 наурыздағы N 28/6-ІІІ "Аббаттандыру, санитарлық жабдықтау, жинау жұмыстарын ұйымдастыру және Астана қаласының аумағында тазалықты қамтамасыз ету қағидалары туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49378/rus
