act_code: '19611'
requisite: Решение Маслихата города Астаны от 30 марта 2004 года № 28/6-III. Зарегистрировано Департаментом юстиции города Астаны 5 мая 2004 года № 326. Утратило силу решением маслихата города Астаны от 20 июля 2017 года № 166/21-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О правилах благоустройства, санитарного содержания, организации уборки и обеспечения чистоты на территории города Астаны
  kaz: Аббатандыру, санитарлық жабдықтау, жинау жұмыстарын ұйымдастыру және Астана қаласының аумағында тазалықты қамтамасыз ету қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-03-29
approved_by:
- '151000000002'
version_date:
  kaz: 2008-03-28
  rus: 2008-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/19611/kaz/28.03.2008
  rus: https://zan.gov.kz/client/#!/doc/19611/rus/28.03.2008
caused_by:
  code: '39201'
  requisite: Решение Маслихата города Астаны от 28 марта 2008 года N 59/10-IV. Зарегистрировано Департаментом юстиции города Астаны 25 апреля 2008 года N 526. Утратило силу решением маслихата города Астаны от 20 июля 2017 года № 166/21-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 30 марта 2004 года N 28/6-III "О правилах благоустройства, санитарного содержания, организации уборки и обеспечения чистоты на территории города Астаны"
    kaz: Астана қаласы мәслихатының 2004 жылғы 30 наурыздағы N 28/6-ІІІ "Аббаттандыру, санитарлық жабдықтау, жинау жұмыстарын ұйымдастыру және Астана қаласының аумағында тазалықты қамтамасыз ету қағидалары туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/39201/rus
