act_code: '45362'
requisite: Решение маслихата города Астаны от 31 марта 2009 года № 203/31-IV. Зарегистрировано Департаментом юстиции города Астаны 21 апреля 2009 года № 571. Утратило силу решением маслихата города Нур-Султана от 26 сентября 2019 года № 430/55-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ставок фиксированного налога на территории города Астаны
  kaz: Астана қаласының аумағында белгіленген салық ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-31
approved_by:
- '151000000002'
version_date:
  kaz: 2009-03-31
  rus: 2009-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/45362/kaz/31.03.2009
  rus: https://zan.gov.kz/client/#!/doc/45362/rus/31.03.2009
