act_code: '225207'
requisite: Решение маслихата города Астаны от 12 декабря 2025 года № 356/47-VIII
title:
  rus: Об утверждении Программы реновации жилища в городе Астане до 2030 года
  kaz: Астана қаласында 2030 жылға дейін тұрғынжайды реновациялау бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2025-12-12
approved_by:
- '151000000002'
version_date:
  kaz: 2025-12-12
  rus: 2025-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/225207/kaz/12.12.2025
  rus: https://zan.gov.kz/client/#!/doc/225207/rus/12.12.2025
