act_code: '38188'
requisite: Решение Маслихата города Астаны от 30 января 2008 года N 48/8-IV. Зарегистрировано Департаментом юстиции города Астаны 3 марта 2008 года N 489. Утратило силу постановлением маслихата города Астаны от 31 марта 2009 года N 202/31-IV
title:
  rus: Об установлении ставок платы за эмиссии в окружающую среду по городу Астане на 2008 год
  kaz: 2008 жылға арналған Астана қаласы бойынша қоршаған ортаға эмиссия үшін төлем ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-30
approved_by:
- '151000000002'
version_date:
  kaz: 2008-07-09
  rus: 2008-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/38188/kaz/09.07.2008
  rus: https://zan.gov.kz/client/#!/doc/38188/rus/09.07.2008
caused_by:
  code: '41561'
  requisite: Решение Маслихата города Астаны от 9 июля 2008 года N 122/18-IV. Зарегистрировано Департаментом юстиции города Астаны 15 августа 2008 года N 544. Утратило силу постановлением маслихата города Астаны от 31 марта 2009 года N 202/31-IV
  title:
    rus: О внесении изменения и дополнения в решение маслихата города Астаны N 48/8-IV от 30 января 2008 года "Об установлении ставок платы за эмиссии в окружающую среду по городу Астане на 2008 год"
    kaz: Астана қаласы мәслихатының 2008 жылғы 30 қаңтардағы N 48/8-ІV "2008 жылға арналған Астана қаласы бойынша қоршаған ортаға эмиссия үшін төлем ставкаларын белгілеу туралы" шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/41561/rus
