act_code: '26113'
requisite: Решение маслихата города Астаны от 17 ноября 2005 года N 197/23-III. Зарегистрировано в Департаменте юстиции г. Астаны 14 декабря 2005 года N 423. Утратило силу решением маслихата города Астаны от 26 августа 2009 года  N 244/37/-IV
title:
  rus: О Программе развития малого предпринимательства города Астаны на 2006-2008 годы
  kaz: Астана қаласының шағын кәсіпкерлігін дамытудың 2006-2008 жылдарға арналған Бағдарламасы туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2005-11-17
approved_by:
- '151000000002'
version_date:
  kaz: 2005-11-17
  rus: 2005-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/26113/kaz/17.11.2005
  rus: https://zan.gov.kz/client/#!/doc/26113/rus/17.11.2005
