act_code: '44332'
requisite: Постановление акимата города Астаны от 29 января 2009 года N 16-82п. Зарегистрировано Департаментом юстиции города Астаны 16 февраля 2009 года N 562. Утратило силу постановлением акимата города Астаны от 6 февраля 2012 года № 06-178
title:
  rus: Об утверждении перечня объектов коммунальной собственности города Астаны, подлежащих приватизации
  kaz: Жекешелендіруге жататын Астана қаласының коммуналдық меншік объектілерінің тізімін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-29
approved_by:
- '151000000001'
version_date:
  kaz: 2009-01-29
  rus: 2009-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/44332/kaz/29.01.2009
  rus: https://zan.gov.kz/client/#!/doc/44332/rus/29.01.2009
