act_code: '55421'
requisite: Решение маслихата города Астаны от 22 сентября 2010 года № 387/51-IV. Зарегистрировано Департаментом юстиции города Астаны 29 октября 2010 года № 652. Утратило силу решением маслихата города Астаны от 6 марта 2019 года № 363/45-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О Правилах предоставления жилищной помощи в городе Астане
  kaz: Астана қаласында тұрғын үй көмегін көрсету ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-09-22
approved_by:
- '151000000002'
version_date:
  kaz: 2013-03-28
  rus: 2013-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/55421/kaz/28.03.2013
  rus: https://zan.gov.kz/client/#!/doc/55421/rus/28.03.2013
caused_by:
  code: '72466'
  requisite: Решение маслихата города Астаны от 28 марта 2013 года № 119/14-V. Зарегистрировано Департаментом юстиции города Астаны 3 мая 2013 года № 775. Утратило силу решением маслихата города Астаны от 6 марта 2019 года № 363/45-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение маслихата города Астаны от 22 сентября 2010 года № 387/51-IV "О Правилах предоставления жилищной помощи в городе Астане"
    kaz: Астана қаласы мәслихатының 2010 жылғы 22 қыркүйектегі № 387/51-ІV "Астана қаласында тұрғын үй көмегін көрсету қағидасы туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/72466/rus
