act_code: '128000'
requisite: Решение маслихата города Астаны от 12 декабря 2018 года № 333/42-VI. Зарегистрировано Департаментом юстиции города Астаны 4 января 2019 года № 1198
title:
  rus: О бюджете города Нур-Султан на 2019-2021 годы
  kaz: Нұр-Сұлтан қаласының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-12
approved_by:
- '151000000002'
version_date:
  kaz: 2019-03-06
  rus: 2019-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/128000/kaz/06.03.2019
  rus: https://zan.gov.kz/client/#!/doc/128000/rus/06.03.2019
caused_by:
  code: '129890'
  requisite: Решение маслихата города Астаны от 6 марта 2019 года № 354/45-VI. Зарегистрировано Департаментом юстиции города Астаны 27 марта 2019 года № 1211
  title:
    rus: О внесении изменений и дополнения в решение маслихата города Астаны от 12 декабря 2018 года № 333/42-VI «О бюджете города Астаны на 2019-2021 годы»
    kaz: «Астана қаласының 2019-2021 жылдарға арналған бюджеті туралы» Астана қаласы мәслихатының 2018 жылғы 12 желтоқсандағы № 333/42-VI шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/129890/rus
