act_code: '128000'
requisite: Решение маслихата города Астаны от 12 декабря 2018 года № 333/42-VI. Зарегистрировано Департаментом юстиции города Астаны 4 января 2019 года № 1198
title:
  rus: О бюджете города Нур-Султан на 2019-2021 годы
  kaz: Нұр-Сұлтан қаласының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-12
approved_by:
- '151000000002'
version_date:
  kaz: 2019-11-15
  rus: 2019-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/128000/kaz/15.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128000/rus/15.11.2019
caused_by:
  code: '136651'
  requisite: Решение маслихата города Нур-Султана от 15 ноября 2019 года № 449/57-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 3 декабря 2019 года № 1251
  title:
    rus: О внесении изменений и дополнения в решение маслихата города Нур-Султан от 12 декабря 2018 года № 333/42-VI «О бюджете города Нур-Султан на 2019-2021 годы»
    kaz: «Нұр-Сұлтан қаласының 2019-2021 жылдарға арналған бюджеті туралы» Нұр-Сұлтан қаласы мәслихатының 2018 жылғы 12 желтоқсандағы № 333/42-VI шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136651/rus
