act_code: '24547'
requisite: "Решение Маслихата города Астаны от 26 мая 2005 года N 143/18-III.\r\nЗарегистрировано Департаментом юстиции города Астаны 1 июля 2005 года N 395. Утратило силу решением маслихата города Астаны от 27 июня 2014 года № 250/36-V"
title:
  rus: О Перечне категорий граждан, нуждающихся в оказании социальной помощи за счет средств бюджета города Астаны
  kaz: Астана қаласы бюджетiнiң қаражаттары есебiнен әлеуметтiк көмек көрсетуге мұқтаж азаматтар санаттарының тiзбесi туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2005-05-26
approved_by:
- '151000000002'
version_date:
  kaz: 2008-04-24
  rus: 2008-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/24547/kaz/24.04.2008
  rus: https://zan.gov.kz/client/#!/doc/24547/rus/24.04.2008
caused_by:
  code: '39520'
  requisite: Решение маслихата города Астаны от 24 апреля 2008 года N 80/14-IV. Зарегистрировано Департаментом юстиции города Астаны от 12 мая 2008 года N 532. Утратило силу решением маслихата города Астаны от 27 июня 2014 года № 250/36-V
  title:
    rus: О внесении изменений и дополнений в решение маслихата города Астаны от 26 мая 2005 года N 143/18-III "О Перечне категорий граждан, нуждающихся в оказании социальной помощи за счет средств бюджета города Астаны"
    kaz: Астана қаласы мәслихатының 2005 жылғы 26 мамырдағы N 143/18-ІІІ "Астана қаласы бюджетінің қаражаттары есебінен әлеуметтік көмек көрсетуге мұқтаж азаматтар санаттарының тізбесі туралы" шешіміне өзгертулер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/39520/rus
