act_code: '24547'
requisite: "Решение Маслихата города Астаны от 26 мая 2005 года N 143/18-III.\r\nЗарегистрировано Департаментом юстиции города Астаны 1 июля 2005 года N 395. Утратило силу решением маслихата города Астаны от 27 июня 2014 года № 250/36-V"
title:
  rus: О Перечне категорий граждан, нуждающихся в оказании социальной помощи за счет средств бюджета города Астаны
  kaz: Астана қаласы бюджетiнiң қаражаттары есебiнен әлеуметтiк көмек көрсетуге мұқтаж азаматтар санаттарының тiзбесi туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2005-05-26
approved_by:
- '151000000002'
version_date:
  kaz: 2012-11-21
  rus: 2012-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/24547/kaz/21.11.2012
  rus: https://zan.gov.kz/client/#!/doc/24547/rus/21.11.2012
caused_by:
  code: '69225'
  requisite: Решение маслихата города Астаны от 21 ноября 2012 года № 84/10-V. Зарегистрировано Департаментом юстиции города Астаны 12 декабря 2012 года № 755. Утратило силу решением маслихата города Астаны от 27 июня 2014 года № 250/36-V
  title:
    rus: О внесении изменения в решение маслихата города Астаны от 26 мая 2005 года № 143/18-III "О Перечне категорий граждан, нуждающихся в оказании социальной помощи за счет средств бюджета города Астаны"
    kaz: Астана қаласы мәслихатының 2005 жылғы 26 мамырдағы № 143/18-III "Астана қаласы бюджетінің қаражаттары есебінен әлеуметтік көмек көрсетуге мұқтаж азаматтар санаттарының тізбесі туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/69225/rus
