act_code: '127072'
requisite: Решение акима города Астаны от 13 декабря 2018 года № 01-21. Зарегистрировано Департаментом юстиции города Астаны 14 декабря 2018 года № 1193. Утратило силу решением акима города Астаны от 21 декабря 2023 года № 1-22 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании границ избирательных участков по городу Астане
  kaz: Астана қаласы бойынша сайлау учаскелерінің шекараларын құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-13
approved_by:
- '151000000003'
version_date:
  kaz: 2020-11-05
  rus: 2020-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/127072/kaz/05.11.2020
  rus: https://zan.gov.kz/client/#!/doc/127072/rus/05.11.2020
caused_by:
  code: '148197'
  requisite: Решение акима города Нур-Султана от 5 ноября 2020 года № 01-50. Зарегистрировано Департаментом юстиции города Нур-Султана 5 ноября 2020 года № 1303. Утратил силу решением акима города Астаны от 21 декабря 2023 года № 1-22 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение акима города Астаны от 13 декабря 2018 года № 01-21 «О границах избирательных участков по городу Нур-Султан»
    kaz: «Нұр-Сұлтан қаласы бойынша сайлау учаскелерінің шекаралары туралы» Астана қаласы әкімінің 2018 жылғы 13 желтоқсандағы № 01-21 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148197/rus
