act_code: '134470'
requisite: Решение маслихата города Нур-Султана от 23 августа 2019 года № 418/54-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 4 сентября 2019 года № 1244. Утратило силу решением маслихата города Астаны от 28 ноября 2025 года № 346/46-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов в городе Астане
  kaz: Астана қаласында тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-08-23
approved_by:
- '150000000002'
version_date:
  kaz: 2023-05-30
  rus: 2023-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/134470/kaz/30.05.2023
  rus: https://zan.gov.kz/client/#!/doc/134470/rus/30.05.2023
caused_by:
  code: '182591'
  requisite: Решение маслихата города Астаны от 30 мая 2023 года № 37/4-VIII. Зарегистрировано Департаментом юстиции города Астаны 7 июня 2023 года № 1342-01. Утратило силу решением маслихата города Астаны от 28 ноября 2025 года № 346/46-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Нур-Султан от 23 августа 2019 года № 418/54-VI «Об определении размера и перечня категорий получателей жилищных сертификатов в городе Нур-Султан»
    kaz: «Нұр-Сұлтан қаласында тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы» Нұр-Сұлтан қаласы мәслихатының 2019 жылғы 23 тамыздағы № 418/54-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182591/rus
