act_code: '134470'
requisite: Решение маслихата города Нур-Султана от 23 августа 2019 года № 418/54-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 4 сентября 2019 года № 1244. Утратило силу решением маслихата города Астаны от 28 ноября 2025 года № 346/46-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов в городе Астане
  kaz: Астана қаласында тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-08-23
approved_by:
- '150000000002'
version_date:
  kaz: 2024-12-11
  rus: 2024-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/134470/kaz/11.12.2024
  rus: https://zan.gov.kz/client/#!/doc/134470/rus/11.12.2024
caused_by:
  code: '204344'
  requisite: Решение маслихата города Астаны от 11 декабря 2024 года № 251/32-VIII. Зарегистрировано Департаментом юстиции города Астаны 18 декабря 2024 года № 1399-01. Утратило силу решением маслихата города Астаны от 28 ноября 2025 года № 346/46-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Нур-Султан от 23 августа 2019 года № 418/54-VI «Об определении размера и перечня категорий получателей жилищных сертификатов в городе Астане»
    kaz: «Астана қаласында тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы» Нұр-Сұлтан қаласы мәслихатының 2019 жылғы 23 тамыздағы № 418/54-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204344/rus
