act_code: '19665'
requisite: "Решение Маслихата города Астаны от 29 апреля 2004 года N 40/7-III.\r\nЗарегистрировано Департаментом юстиции города Астаны 11 мая 2004 года N 327. Утратило силу - решением Маслихата города Астаны от 21 сентября 2006 года N 283/35-III"
title:
  rus: О Правилах организации работы и взаимодействия государственных органов города Астаны по изъятию (выкупу) земельных участков (права землепользования)
  kaz: Астана қаласы мемлекеттік органдарының жер учаскелерін (жер пайдалану құқығын) алып қою (сатып алу) жөніндегі жұмыстары мен қарым-қатынастарын ұйымдастыру Ережелері туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-04-28
approved_by:
- '151000000002'
version_date:
  kaz: 2005-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/19665/kaz/30.06.2005
caused_by:
  code: '24876'
  requisite: Решение Маслихата города Астаны от 30 мая 2005 года N 168/20-III. Зарегистрировано Департаментом юстиции города Астаны 28 июля 2005 года N 402. Утратило силу решением маслихата города Астаны от 12 июля 2007 года N 408/50-III
  title:
    rus: О внесении изменений в некоторые решения маслихата по вопросам землепользования
    kaz: Жер пайдалану мәселелері туралы мәслихаттың кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/24876/rus
