act_code: '223677'
requisite: Решение маслихата города Астаны от 19 марта 2026 года № 393/51-VIII. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 апреля 2026 года № 38259
title:
  rus: Об утверждении правил организации дорожного движения в городе Астане в части, не урегулированной правилами дорожного движения
  kaz: Жол жүрісі қағидаларында реттелмеген бөлікте Астана қаласында жол жүрісін ұйымдастыру қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2026-03-19
approved_by:
- '151000000002'
version_date:
  kaz: 2026-03-19
  rus: 2026-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/223677/kaz/19.03.2026
  rus: https://zan.gov.kz/client/#!/doc/223677/rus/19.03.2026
