act_code: '133026'
requisite: Решение маслихата города Нур-Султана от 27 июня 2019 года № 395/52-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 3 июля 2019 года № 1235. Утратило силу решением маслихата города Астаны от 30 июня 2026 года № 434/56-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении ставок платы за негативное воздействие на окружающую среду по городу Астане
  kaz: Астана қаласы бойынша қоршаған ортаға жағымсыз әсер еткені үшін төлемақы ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-27
approved_by:
- '150000000002'
version_date:
  kaz: 2023-06-30
  rus: 2023-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/133026/kaz/30.06.2023
  rus: https://zan.gov.kz/client/#!/doc/133026/rus/30.06.2023
caused_by:
  code: '183884'
  requisite: Решение маслихата города Астаны от 30 июня 2023 года № 44/5-VIII. Утратило силу решением маслихата города Астаны от 26 июня 2026 года № 435/56-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Нур-Султана от 27 июня 2019 года № 395/52-VI «Об утверждении ставок платы за эмиссии в окружающую среду по городу Нур-Султан»
    kaz: Нұр-Сұлтан қаласы мәслихатының 2019 жылғы 27 маусымдағы № 395/52-VI «Нұр-Сұлтан қаласы бойынша қоршаған ортаға эмиссия үшін төлемақы ставкаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183884/rus
