act_code: '50173'
requisite: Решение маслихата города Астаны от 21 декабря 2009 года № 284/42-IV. Зарегистрировано Департаментом юстиции города Астаны 19 января 2010 года № 610. Утратило силу решением маслихата города Астаны от 12 мая 2011 года № 449/62-IV
title:
  rus: О бюджете города Астаны на 2010-2012 годы
  kaz: Астана қаласының 2010-2012 жылдарға арналған бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '151000000002'
version_date:
  kaz: 2010-09-22
  rus: 2010-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/50173/kaz/22.09.2010
  rus: https://zan.gov.kz/client/#!/doc/50173/rus/22.09.2010
caused_by:
  code: '54677'
  requisite: Решение маслихата города Астаны от 22 сентября 2010 года N 385/51-IV. Зарегистрировано Департаментом юстиции города Астаны 1 октября 2010 года N 649. Утратило силу решением маслихата города Астаны от 12 мая 2011 года № 449/62-IV
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 21 декабря 2009 года N 284/42-IV "О бюджете города Астаны на 2010-2012 годы"
    kaz: '"Астана қаласының 2010-2012 жылдарға арналған бюджеті туралы" Астана қаласы мәслихатының 2009 жылғы 21 желтоқсандағы N 284/42-IV шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/54677/rus
