act_code: '50173'
requisite: Решение маслихата города Астаны от 21 декабря 2009 года № 284/42-IV. Зарегистрировано Департаментом юстиции города Астаны 19 января 2010 года № 610. Утратило силу решением маслихата города Астаны от 12 мая 2011 года № 449/62-IV
title:
  rus: О бюджете города Астаны на 2010-2012 годы
  kaz: Астана қаласының 2010-2012 жылдарға арналған бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '151000000002'
version_date:
  kaz: 2009-12-21
  rus: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/50173/kaz/21.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50173/rus/21.12.2009
