act_code: '56990'
requisite: Решение маслихата города Астаны от 13 декабря 2010 года № 410/54-IV. Зарегистрировано Департаментом юстиции города Астаны 24 января 2011 года № 666. Утратило силу решением маслихата города Астаны от 27 июня 2014 года № 250/36-V
title:
  rus: О Правилах оказания социальной помощи отдельным категориям нуждающихся граждан города Астаны
  kaz: Астана қаласындағы мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-13
approved_by:
- '151000000002'
version_date:
  kaz: 2012-06-26
  rus: 2012-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/56990/kaz/26.06.2012
  rus: https://zan.gov.kz/client/#!/doc/56990/rus/26.06.2012
caused_by:
  code: '66890'
  requisite: Решение маслихата города Астаны от 26 июня 2012 года № 48/5-V. Зарегистрировано Департаментом юстиции города Астаны 31 июля 2012 года № 737. Утратило силу решением маслихата города Астаны от 27 июня 2014 года № 250/36-V
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 13 декабря 2010 года № 410/54-IV "О Правилах оказания социальной помощи отдельным категориям нуждающихся граждан города Астаны"
    kaz: Астана қаласы мәслихатының 2010 жылғы 13 желтоқсандағы № 410/54-ІV "Астана қаласындағы мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету қағидасы туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/66890/rus
