act_code: '162035'
requisite: Решение маслихата города Нур-Султана от 15 декабря 2021 года № 114/16-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 декабря 2021 года № 25946
title:
  rus: О бюджете города Астаны на 2022-2024 годы
  kaz: Астана қаласының 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-15
approved_by:
- '150000000002'
version_date:
  kaz: 2021-12-15
  rus: 2021-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/162035/kaz/15.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162035/rus/15.12.2021
