act_code: '11173'
requisite: Решение Маслихата города Астаны от 25 декабря 2001 года № 129/26-II. Зарегистрировано управлением юстиции города Астаны 1 февраля 2002 года № 167. Утратило силу решением маслихата города Астаны от 29 января 2009 года № 184/30-IV
title:
  rus: О ставках земельного налога по городу Астане
  kaz: Астана қаласы бойынша жер салығының мөлшерлемесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-25
approved_by:
- '151000000002'
version_date:
  kaz: 2001-12-25
  rus: 2001-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/11173/kaz/25.12.2001
  rus: https://zan.gov.kz/client/#!/doc/11173/rus/25.12.2001
