act_code: '137833'
requisite: Решение маслихата города Нур-Султана от 25 декабря 2019 года № 476/60-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 30 декабря 2019 года № 1256. Утратило силу решением маслихата города Астаны от 14 февраля 2025 года № 269/34-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении тарифов на сбор, вывоз, утилизацию, переработку и захоронение твердых бытовых отходов в городе Нур-Султан
  kaz: Нұр-Сұлтан қаласында қатты тұрмыстық қалдықтарды жинауға, әкетуге, кәдеге жаратуға, қайта өңдеуге және көмуге арналған тарифтерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '150000000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/137833/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137833/rus/25.12.2019
