act_code: '19666'
requisite: "Решение Маслихата города Астаны от 29 апреля 2004 года N 39/7-III.\r\nЗарегистрировано Департаментом юстиции города Астаны 11 мая 2004 года N 328. Утратило силу - решением Маслихата города Астаны от 12 октября 2006 года N 294/37-III"
title:
  rus: О Правилах предоставления прав на земельные участки в городе Астане
  kaz: Астана қаласындағы жер учаскелерiне құқық табыстау Ережелерiн бекiту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-04-28
approved_by:
- '151000000002'
version_date:
  kaz: 2005-03-29
  rus: 2005-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/19666/kaz/29.03.2005
  rus: https://zan.gov.kz/client/#!/doc/19666/rus/29.03.2005
caused_by:
  code: '23585'
  requisite: "Решение Маслихата города Астаны от 29 марта 2005 года N 129/17-III.\r\nЗарегистрировано Департаментом юстиции города Астаны 14 апреля 2005 года N 383. Утратило силу - решением Маслихата города Астаны от 12 октября 2006 года N 294/37-III"
  title:
    rus: О внесении изменения в решение маслихата города Астаны от 29 апреля 2004 года N 39/7-III "О Правилах предоставления прав на земельные участки в городе Астане" (зарегистрировано департаментом юстиции г. Астаны 11 мая 2004 года за N 328)
    kaz: Астана қаласы мәслихатының«"Астана қаласында жер учаскелеріне құқық беру ережесі туралы"»2004 жылғы 29 сәуірдегі N 39/7-ІІІ шешіміне (Астана қаласының әділет департаменті 2004 жылғы 11 мамырда N 328 тіркелген) өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/23585/rus
