act_code: '117535'
requisite: Решение маслихата города Астаны от 12 декабря 2017 года № 221/25-VI. Зарегистрировано Департаментом юстиции города Астаны 4 января 2018 года № 1149. Утратило силу решением маслихата города Астаны от 3 октября 2023 года № 84/10-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О Правилах оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Астаны
  kaz: Астана қаласында әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-12-12
approved_by:
- '151000000002'
version_date:
  kaz: 2019-03-06
  rus: 2019-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/117535/kaz/06.03.2019
  rus: https://zan.gov.kz/client/#!/doc/117535/rus/06.03.2019
caused_by:
  code: '130394'
  requisite: Решение маслихата города Астаны от 6 марта 2019 года № 361/45-VI. Зарегистрировано Департаментом юстиции города Астаны 8 апреля 2019 года № 1217. Утратило силу решением маслихата города Астаны от 3 октября 2023 года № 84/10-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 12 декабря 2017 года № 221/25-VI «О Правилах оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Астаны»
    kaz: «Астана қаласында әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасы туралы» Астана қаласы мәслихатінің 2017 жылғы 12 желтоқсандағы № 221/25-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130394/rus
