act_code: '117535'
requisite: Решение маслихата города Астаны от 12 декабря 2017 года № 221/25-VI. Зарегистрировано Департаментом юстиции города Астаны 4 января 2018 года № 1149. Утратило силу решением маслихата города Астаны от 3 октября 2023 года № 84/10-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О Правилах оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Астаны
  kaz: Астана қаласында әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-12-12
approved_by:
- '151000000002'
version_date:
  kaz: 2021-11-24
  rus: 2021-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/117535/kaz/24.11.2021
  rus: https://zan.gov.kz/client/#!/doc/117535/rus/24.11.2021
caused_by:
  code: '161667'
  requisite: Решение маслихата города Нур-Султана от 24 ноября 2021 года № 105/15-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 декабря 2021 года № 25765. Утратило силу решением маслихата города Астаны от 3 октября 2023 года № 84/10-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 12 декабря 2017 года № 221/25-VI «О Правилах оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Нур-Султан»
    kaz: «Нұр-Сұлтан қаласының әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасы туралы» Астана қаласы мәслихатының 2017 жылғы 12 желтоқсандағы № 221/25-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161667/rus
