act_code: '98836'
requisite: Решение маслихата города Астаны от 23 декабря 2015 года № 449/62-V. Зарегистрировано Департаментом юстиции города Астаны 28 января 2016 года № 998
title:
  rus: О Правилах содержания животных на территории города Астаны
  kaz: Астана қаласының аумағында жануарларды ұстау қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-12-23
approved_by:
- '151000000002'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/98836/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/98836/rus/29.03.2024
caused_by:
  code: '195455'
  requisite: Решение маслихата города Астаны от 29 марта 2024 года № 170/20-VIII. Зарегистрировано Департаментом юстиции города Астаны 9 апреля 2024 года № 1376-01
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 23 декабря 2015 года № 449/62-V «О Правилах содержания животных на территории города Астаны»
    kaz: «Астана қаласының аумағында жануарларды ұстау қағидалары туралы» Астана қаласы мәслихатының 2015 жылғы 23 желтоқсандағы № 449/62-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195455/rus
