act_code: '111384'
requisite: Решение маслихата города Астаны от 17 марта 2017 года № 115/17-VI. Зарегистрировано Департаментом юстиции города Астаны 12 апреля 2017 года № 1098
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью города Астаны
  kaz: Астана қаласының мүгедектігі бар балалар қатарындағы мүмкіндігі шектеулі балаларды үйде оқытуға жұмсалған шығындарды өндіріп алу тәртібі мен мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-03-17
approved_by:
- '151000000002'
version_date:
  kaz: 2019-03-06
  rus: 2019-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/111384/kaz/06.03.2019
  rus: https://zan.gov.kz/client/#!/doc/111384/rus/06.03.2019
caused_by:
  code: '130157'
  requisite: Решение маслихата города Астаны от 6 марта 2019 года № 360/45-VI. Зарегистрировано Департаментом юстиции города Астаны 5 апреля 2019 года № 1216
  title:
    rus: О внесении изменений и дополнения в решение маслихата города Астаны от 17 марта 2017 № 115/17-VI «О порядке и размерах возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов города Астаны»
    kaz: «Астана қаласының мүгедектер қатарындағы мүмкіндігі шектеулі балаларды үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшері туралы» Астана қаласы мәслихатының 2017 жылғы 17 наурыздағы № 115/17-VI шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130157/rus
