act_code: '62834'
requisite: Решение маслихата города Астаны от 27 декабря 2011 года № 538/77-IV. Зарегистрировано Департаментом юстиции города Астаны 19 января 2011 года № 711. Утратило силу решением маслихата города Астаны от 12 декабря 2017 года № 220/25-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О Правилах общего водопользования на водных объектах города Астаны
  kaz: Астана қаласының су объектілерінде ортақ су пайдалану қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2011-12-27
approved_by:
- '151000000002'
version_date:
  kaz: 2011-12-27
  rus: 2011-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/62834/kaz/27.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62834/rus/27.12.2011
