act_code: '62834'
requisite: Решение маслихата города Астаны от 27 декабря 2011 года № 538/77-IV. Зарегистрировано Департаментом юстиции города Астаны 19 января 2011 года № 711. Утратило силу решением маслихата города Астаны от 12 декабря 2017 года № 220/25-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О Правилах общего водопользования на водных объектах города Астаны
  kaz: Астана қаласының су объектілерінде ортақ су пайдалану қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2011-12-27
approved_by:
- '151000000002'
version_date:
  kaz: 2015-06-24
  rus: 2015-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/62834/kaz/24.06.2015
  rus: https://zan.gov.kz/client/#!/doc/62834/rus/24.06.2015
caused_by:
  code: '92245'
  requisite: Решение Маслихата города Астаны от 24 июня 2015 года № 384/54-V. Зарегистрировано Департаментом юстиции города Астаны 29 июля 2015 года № 928. Утратило силу решением маслихата города Астаны от 12 декабря 2017 года № 220/25-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата города Астаны от 27 декабря 2011 года № 538/77-IV «О Правилах общего водопользования на водных объектах города Астаны»
    kaz: «Астана қаласының су объектілерінде ортақ су пайдалану қағидасы туралы» Астана қаласы мәслихатының 2011 жылғы 27 желтоқсандағы № 538/77-IV шешiмiне өзгерiс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/92245/rus
