act_code: '31973'
requisite: Решение Маслихата города Астаны от 9 февраля 2007 года N 344/43-III. Зарегистрированно в Департаменте юстиции города Астаны 21 февраля 2007 года N 461. Утратило силу решением маслихата города Астаны от 29 января 2009 года N 185/30-IV.
title:
  rus: Об утверждении поправочных коэффициентов и границ зон для определения кадастровой (оценочной) стоимости земельных участков при их предоставлении в частную собственность, при сдаче государством или государственными землепользователями в аренду
  kaz: Жер учаскелері жеке меншікке берілген кезде, мемлекет немесе мемлекеттік жер пайдаланушылар жалға берген кезде жер учаскесінің кадастрлік (бағалау) құнын анықтау үшін түзету коэффициенттері мен шекара аймақтарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-02-09
approved_by:
- '151000000002'
version_date:
  kaz: 2007-02-09
  rus: 2007-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/31973/kaz/09.02.2007
  rus: https://zan.gov.kz/client/#!/doc/31973/rus/09.02.2007
