act_code: '137831'
requisite: Решение маслихата города Нур-Султана от 12 декабря 2019 года № 456/58-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 30 декабря 2019 года № 1252
title:
  rus: О бюджете города Нур-Султана на 2020-2022 годы
  kaz: Нұр-Сұлтан қаласының 2020-2022 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-12
approved_by:
- '150000000002'
version_date:
  kaz: 2019-12-12
  rus: 2019-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/137831/kaz/12.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137831/rus/12.12.2019
