act_code: '9840'
requisite: Решение Маслихата города Астаны от 10 августа 2001 года N 107/22-II. Зарегистрировано Управлением юстиции г. Астаны 27 августа 2001 года за N 142. Утратило силу - решением Маслихата города Астаны от 29 марта 2006 года N 232/30-III
title:
  rus: О Программе "Снос аварийных и ветхих жилых домов в г. Астане на 2002-2005 годы"
  kaz: '"Астана қаласында 2002-2005 жылдары авариялық және ескірген тұрғын үйлерді бұзып алу" бағдарламасы туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-08-09
approved_by:
- '151000000002'
version_date:
  kaz: 2001-08-09
  rus: 2001-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/9840/kaz/09.08.2001
  rus: https://zan.gov.kz/client/#!/doc/9840/rus/09.08.2001
