act_code: '26114'
requisite: Решение маслихата города Астаны от 17 ноября 2005 года N 198/23-III. Зарегистрировано в Департаменте юстиции г. Астаны 14 декабря 2005 года N 424. Утратило силу решением маслихата города Астаны от 31 марта 2009 года N 194/31-IV
title:
  rus: О Программе развития туристской отрасли в городе Астане на 2006-2008 годы
  kaz: Астана қаласында туристік саланы дамытудың 2006-2008 жылдарға арналған Бағдарламасы туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2005-11-17
approved_by:
- '151000000002'
version_date:
  kaz: 2006-12-26
  rus: 2006-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/26114/kaz/26.12.2006
  rus: https://zan.gov.kz/client/#!/doc/26114/rus/26.12.2006
caused_by:
  code: '31620'
  requisite: Решение Маслихата города Астаны от 26 декабря 2006 года N 330/41-III. Зарегистрировано в Департаменте юстиции города Астаны от 31 января 2007 года N 457. Утратило силу решением маслихата города Астаны от 31 марта 2009 года N 194/31-IV
  title:
    rus: О внесении изменений и дополнений в решение маслихата города Астаны от 17 ноября 2005 года N 198/23-III "О Программе развития туристской отрасли в городе Астане на 2006-2008 годы"
    kaz: Астана қаласы мәслихатының 2005 жылғы 17 қарашадағы N 198/23-III "Астана қаласында туристік саланы дамытудың 2006-2008 жылдарға арналған Бағдарламасы туралы" шешіміне өзгерістер және толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/31620/rus
