act_code: '131228'
requisite: Решение маслихата города Нур-Султана от 3 мая 2019 года № 380/49-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 6 мая 2019 года № 1226. Утратило силу решением маслихата города Нур-Султана от 30 июня 2020 года № 515/68-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об оказании дополнительной социальной помощи участникам и инвалидам Великой Отечественной войны города Нур-Султан ко Дню Победы
  kaz: Нұр-Сұлтан қаласы Ұлы Отан соғысының қатысушылары мен мүгедектеріне Жеңіс күніне орай қосымша әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-03
approved_by:
- '150000000002'
version_date:
  kaz: 2019-05-03
  rus: 2019-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/131228/kaz/03.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131228/rus/03.05.2019
