act_code: '53781'
requisite: Решение маслихата города Астаны от 17 июня 2010 года № 367/49-IV. Зарегистрировано Департаментом юстиции города Астаны 30 июля 2010 года № 644. Утратил силу решением маслихата города Астаны от 20 июля 2017 года № 181/21-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О Правилах содержания зданий и сооружений жилищно-гражданского назначения, инженерных коммуникаций в городе Астане
  kaz: Астана қаласының тұрғын үй-азаматтық маңызы бар ғимараттары мен құрылыстарын, инженерлік коммуникацияларды күтіп ұстау Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-17
approved_by:
- '151000000002'
version_date:
  kaz: 2014-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/53781/kaz/27.06.2014
