act_code: '195114'
requisite: Решение маслихата города Астаны от 7 марта 2024 года № 149/19-VIII
title:
  rus: Об утверждении Правил регулирования миграционных процессов в городе Астане
  kaz: Астана қаласындағы көші-қон процестерін реттеу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-07
approved_by:
- '151000000002'
version_date:
  kaz: 2024-03-07
  rus: 2024-03-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/195114/kaz/07.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195114/rus/07.03.2024
