act_code: '187389'
requisite: Решение маслихата города Астаны от 3 октября 2023 года № 84/10-VIII. Зарегистрировано Департаментом юстиции города Астаны 19 октября 2023 года № 1357-01
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан города Астаны
  kaz: Астана қаласында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-03
approved_by:
- '151000000002'
version_date:
  kaz: 2024-06-28
  rus: 2024-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/187389/kaz/28.06.2024
  rus: https://zan.gov.kz/client/#!/doc/187389/rus/28.06.2024
caused_by:
  code: '198539'
  requisite: Решение маслихата города Астаны от 28 июня 2024 года № 194/24-VIII. Зарегистрировано Департаментом юстиции города Астаны 5 июля 2024 года № 1387-01
  title:
    rus: О внесении изменений и дополнений в решение маслихата города Астаны от 3 октября 2023 года № 84/10-VIII «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан города Астаны»
    kaz: «Астана қаласында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасын бекіту туралы» Астана қаласы мәслихатының 2023 жылғы 3 қазандағы № 84/10-VIII шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198539/rus
