act_code: '207359'
requisite: Решение маслихата города Астаны от 14 февраля 2025 года № 272/34-VIII
title:
  rus: Об утверждении Правил содержания и выгула домашних животных в городе Астане
  kaz: Астана қаласында үй жануарларын ұстаудың және серуендетудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2025-02-14
approved_by:
- '151000000002'
version_date:
  kaz: 2025-02-14
  rus: 2025-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/207359/kaz/14.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207359/rus/14.02.2025
