act_code: '44602'
requisite: Решение маслихата города Астаны от 29 января 2009 года № 184/30-IV. Зарегистрировано Департаментом юстиции города Астаны 5 марта 2009 года № 565. Утратило силу решением маслихата города Астаны от 06 декабря 2012 года № 94/11-V
title:
  rus: О схеме зонирования земель для целей налогообложения и процентах повышения (понижения) базовых ставок земельного налога
  kaz: Жер салығының базалық ставкаларын арттыру (төмендету) пайыздары және салық салу мақсаттары үшін жерлерді аймақтарға бөлу сұлбасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-29
approved_by:
- '151000000002'
version_date:
  kaz: 2009-01-29
  rus: 2009-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/44602/kaz/29.01.2009
  rus: https://zan.gov.kz/client/#!/doc/44602/rus/29.01.2009
