act_code: '86047'
requisite: Решение маслихата города Астаны от 11 декабря 2014 года № 307/45-V. Зарегистрировано Департаментом юстиции города Астаны 16 января 2015 года № 877. Утратило силу решением маслихата города Астаны от 9 ноября 2018 года № 325/41-VI (вводится в действие по истечении десяти    календарных дней после дня его первого официального опубликования)
title:
  rus: О базовых ставках налога на земли, выделенные под автостоянки (паркинги) города Астаны
  kaz: Астана қаласында автотұрақтарға (паркингтерге) бөлінген жер үшін салықтың базалық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-11
approved_by:
- '151000000002'
version_date:
  kaz: 2014-12-11
  rus: 2014-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/86047/kaz/11.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86047/rus/11.12.2014
