act_code: '70067'
requisite: Решение маслихата города Астаны от 06 декабря 2012 года № 94/11-V. Зарегистрировано Департаментом юстиции города Астаны 11 января 2013 года № 763. Утратило силу решением маслихата города Астаны от 9 ноября 2018 года № 326/41-VI (вводится в действие с 1 января 2019 года)
title:
  rus: О  схеме зонирования земель для целей налогообложения и процентах  повышения (понижения) базовых ставок земельного налога
  kaz: Жер салығының базалық ставкаларын арттыру (төмендету) пайыздары және салық салу мақсаттары үшін жерлерді аймақтарға бөлу сұлбасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-05
approved_by:
- '151000000002'
version_date:
  kaz: 2012-12-06
  rus: 2012-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/70067/kaz/06.12.2012
  rus: https://zan.gov.kz/client/#!/doc/70067/rus/06.12.2012
repealed_on: 2019-01-01
repealed_by:
  code: '127991'
  requisite: Решение маслихата города Астаны от 9 ноября 2018 года № 326/41-VI. Зарегистрировано Департаментом юстиции города Астаны 29 декабря 2018 года № 1197
  title:
    rus: О схеме зонирования земель для целей налогообложения и процентах повышения (понижения) базовых ставок земельного налога
    kaz: Салық салу мақсатында жерді аймаққа бөлу схемасы және жер салығының базалық мөлшерлемелерін арттыру (азайту) пайыздары туралы
  link: https://zan.gov.kz/client/#!/doc/127991/rus
