act_code: '32329'
requisite: Решение Маслихата города Астаны от 9 февраля 2007 года N 341/43-III. Зарегистрировано Департаментом юстиции города Астаны 14 марта 2007 года N 464. Утратило силу Решение маслихата города Астаны от 23 декабря 2015 года № 447/62-V
title:
  rus: О Правилах содержания собак и кошек в городе Астане
  kaz: Астана қаласында иттер мен мысықтарды ұстау Ережесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-02-09
approved_by:
- '151000000002'
version_date:
  rus: 2009-06-28
source:
  rus: https://zan.gov.kz/client/#!/doc/32329/rus/28.06.2009
