act_code: '144594'
requisite: Решение маслихата города Нур-Султана от 30 июня 2020 года № 512/68-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 8 июля 2020 года № 1275. Утратил силу решением маслихата города Астаны от 26 декабря 2023 года № 133/16-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний в городе Нур-Султане
  kaz: Нұр-Сұлтан қаласында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды анықтау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-30
approved_by:
- '150000000002'
version_date:
  kaz: 2020-06-30
  rus: 2020-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/144594/kaz/30.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144594/rus/30.06.2020
