act_code: '15375'
requisite: Решение Маслихата города Астаны от 8 апреля 2003 года N 219/42-II. Зарегистрировано Управлением юстиции города Астаны 15 мая 2003 года N 264. Утратило силу - решением Маслихата города Астаны от 21 сентября 2006 года N 285/35-III
title:
  rus: О Программе развития и поддержки малого предпринимательства города Астаны на 2003-2005 годы
  kaz: 2003-2005 жылдарға арналған Астана қаласының шағын кәсіпкерлікті дамыту және қолдау бағдарламасы туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2003-04-07
approved_by:
- '151000000002'
version_date:
  kaz: 2003-04-07
  rus: 2003-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/15375/kaz/07.04.2003
  rus: https://zan.gov.kz/client/#!/doc/15375/rus/07.04.2003
