act_code: '117898'
requisite: Решение маслихата города Астаны от 12 декабря 2017 года № 220/25-VI. Зарегистрировано Департаментом юстиции города Астаны 11 января 2018 года № 1150. Утратило силу решением маслихата города Астаны от 12 ноября 2025 года № 338/45-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О Правилах общего водопользования города Нур-Султана
  kaz: Нұр-Сұлтан қаласының ортақ су пайдалану қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-12-12
approved_by:
- '151000000002'
version_date:
  kaz: 2020-06-30
  rus: 2020-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/117898/kaz/30.06.2020
  rus: https://zan.gov.kz/client/#!/doc/117898/rus/30.06.2020
caused_by:
  code: '144614'
  requisite: Решение маслихата города Нур-Султана от 30 июня 2020 года № 511/68-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 8 июля 2020 года № 1276. Утратило силу решением маслихата города Астаны от 12 ноября 2025 года № 338/45-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в решение маслихата города Астаны от 12 декабря 2017 года № 220/25-VI «О Правилах общего водопользования города Астаны»
    kaz: «Астана қаласының ортақ су пайдалану қағидалары туралы» Астана қаласы мәслихатының 2017 жылғы 12 желтоқсандағы № 220/25-VI шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144614/rus
