act_code: '117898'
requisite: Решение маслихата города Астаны от 12 декабря 2017 года № 220/25-VI. Зарегистрировано Департаментом юстиции города Астаны 11 января 2018 года № 1150. Утратило силу решением маслихата города Астаны от 12 ноября 2025 года № 338/45-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О Правилах общего водопользования города Нур-Султана
  kaz: Нұр-Сұлтан қаласының ортақ су пайдалану қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-12-12
approved_by:
- '151000000002'
version_date:
  kaz: 2017-12-12
  rus: 2017-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/117898/kaz/12.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117898/rus/12.12.2017
