act_code: '35598'
requisite: Решение маслихата города Астаны от 17 октября 2007 года N 15/4-IV. Зарегистрировано Департаментом юстиции города Астаны 5 ноября 2007 года N 476. Утратило силу решением маслихата города Астаны от 13 декабря 2010 года № 416/54-IV
title:
  rus: О Правилах оказания социальной помощи отдельным категориям нуждающихся граждан города Астаны в связи с удорожанием цен на продукты питания
  kaz: Азық-түлікке бағалардың қымбаттануына байланысты Астана қаласындағы мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету Қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-10-17
approved_by:
- '151000000002'
version_date:
  kaz: 2009-03-31
  rus: 2009-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/35598/kaz/31.03.2009
  rus: https://zan.gov.kz/client/#!/doc/35598/rus/31.03.2009
caused_by:
  code: '45520'
  requisite: Решение маслихата города Астаны от 31 марта 2009 года N 198/31-IV. Зарегистрировано Департаментом юстиции города Астаны 27 апреля 2009 года N 573. Утратило силу решением маслихата города Астаны от 13 декабря 2010 года № 416/54-IV
  title:
    rus: О внесении изменения и дополнения в решение маслихата города Астаны от 17 октября 2007 года № 15/4-IV "О Правилах оказания социальной помощи отдельным категориям нуждающихся граждан города Астаны в связи с удорожанием цен на продукты питания"
    kaz: Астана қаласы мәслихатының 2007 жылғы 17 қазандағы N 15/4-ІV "Азық-түлікке бағалардың қымбаттауына байланысты Астана қаласындағы мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету Қағидалары туралы" шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45520/rus
