act_code: '35598'
requisite: Решение маслихата города Астаны от 17 октября 2007 года N 15/4-IV. Зарегистрировано Департаментом юстиции города Астаны 5 ноября 2007 года N 476. Утратило силу решением маслихата города Астаны от 13 декабря 2010 года № 416/54-IV
title:
  rus: О Правилах оказания социальной помощи отдельным категориям нуждающихся граждан города Астаны в связи с удорожанием цен на продукты питания
  kaz: Азық-түлікке бағалардың қымбаттануына байланысты Астана қаласындағы мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету Қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-10-17
approved_by:
- '151000000002'
version_date:
  rus: 2008-04-24
source:
  rus: https://zan.gov.kz/client/#!/doc/35598/rus/24.04.2008
caused_by:
  code: '39620'
  requisite: Решение Маслихата города Астаны от 24 апреля 2008 года N 79/14-IV. Зарегистрировано Департаментом юстиции города Астаны 16 мая 2008 года N 535. Утратило силу решением маслихата города Астаны от 13 декабря 2010 года № 416/54-IV
  title:
    rus: О внесении изменения в решение маслихата города Астаны от 17 октября 2007 года N 15/4-IV "О Правилах оказания социальной помощи отдельным категориям нуждающихся граждан города Астаны в связи с удорожанием цен на продукты питания"
    kaz: Астана қаласы мәслихатының 2007 жылғы 17 қазандағы N 15/4-ІV "Азық-түлікке бағалардың қымбаттауына байланысты Астана қаласындағы мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету Қағидасы туралы" шешіміне өзгерту енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/39620/rus
