act_code: '35598'
requisite: Решение маслихата города Астаны от 17 октября 2007 года N 15/4-IV. Зарегистрировано Департаментом юстиции города Астаны 5 ноября 2007 года N 476. Утратило силу решением маслихата города Астаны от 13 декабря 2010 года № 416/54-IV
title:
  rus: О Правилах оказания социальной помощи отдельным категориям нуждающихся граждан города Астаны в связи с удорожанием цен на продукты питания
  kaz: Азық-түлікке бағалардың қымбаттануына байланысты Астана қаласындағы мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету Қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-10-17
approved_by:
- '151000000002'
version_date:
  kaz: 2008-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/35598/kaz/24.02.2008
