act_code: '49382'
requisite: Решение маслихата города Астаны от 6 ноября 2009 года № 257/39-IV. Зарегистрировано Департаментом юстиции города Астаны 15 декабря 2009 года № 606
title:
  rus: О Правилах присвоения звания «Астана қаласының құрметті азаматы»
  kaz: «Астана қаласының құрметті азаматы» атағын беру Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-06
approved_by:
- '151000000002'
version_date:
  kaz: 2023-06-30
  rus: 2023-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/49382/kaz/30.06.2023
  rus: https://zan.gov.kz/client/#!/doc/49382/rus/30.06.2023
caused_by:
  code: '184060'
  requisite: Решение маслихата города Астаны от 30 июня 2023 года № 46/5-VIII. Зарегистрировано Департаментом юстиции города Астаны 17 июля 2023 года № 1347-01
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 6 ноября 2009 года № 257/39-IV«О Правилах присвоения звания «Нұр-Сұлтан қаласының құрметті азаматы»
    kaz: «Нұр-Сұлтан қаласының құрметті азаматы» атағын беру Қағидасы туралы» Астана қаласы мәслихатының 2009 жылғы 6 қарашадағы № 257/39-IV шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184060/rus
