act_code: '49382'
requisite: Решение маслихата города Астаны от 6 ноября 2009 года № 257/39-IV. Зарегистрировано Департаментом юстиции города Астаны 15 декабря 2009 года № 606
title:
  rus: О Правилах присвоения звания «Астана қаласының құрметті азаматы»
  kaz: «Астана қаласының құрметті азаматы» атағын беру Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-06
approved_by:
- '151000000002'
version_date:
  kaz: 2019-07-02
  rus: 2019-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/49382/kaz/02.07.2019
  rus: https://zan.gov.kz/client/#!/doc/49382/rus/02.07.2019
caused_by:
  code: '133029'
  requisite: Решение маслихата города Нур-Султана от 2 июля 2019 года № 411/53-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 5 июля 2019 года № 1237
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 6 ноября 2009 года № 257/39-IV «О Правилах присвоения звания «Астана қаласының құрметті азаматы»
    kaz: Астана қаласы мәслихатының 2009 жылғы 6 қарашадағы № 257/39-IV «Астана қаласының құрметті азаматы» атағын беру Қағидасы туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133029/rus
