act_code: '39284'
requisite: Решение маслихата города Астаны от 24 апреля 2008 года N 76/14-IV. Зарегистрировано Департаментом юстиции города Астаны 30 апреля 2008 года N 529. Утратило силу решением маслихата города Астаны от 27 июня 2014 года № 258/36-V
title:
  rus: О Правилах организации закупа жилья на объектах незавершенного строительства города Астаны
  kaz: Астана қаласындағы құрылысы аяқталмаған объектілерден тұрғын үй сатып алуды ұйымдастыру Ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2008-04-24
approved_by:
- '151000000002'
version_date:
  kaz: 2009-11-06
  rus: 2009-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/39284/kaz/06.11.2009
  rus: https://zan.gov.kz/client/#!/doc/39284/rus/06.11.2009
caused_by:
  code: '49380'
  requisite: Решение маслихата города Астаны от 6 ноября 2009 года N 269/39-IV. Зарегистрировано Департаментом юстиции города Астаны 15 декабря 2009 года N 604. Утратило силу решением маслихата города Астаны от 27 июня 2014 года № 258/36-V
  title:
    rus: О внесении изменения в решение маслихата города Астаны от 24 апреля 2008 года № 76/14-IV "О Правилах организации закупа жилья на объектах незавершенного строительства города Астаны"
    kaz: Астана қаласы мәслихатының 2008 жылғы 24 сәуірдегі N 76/14-ІV "Астана қаласындағы құрылысы аяқталмаған объектілерден тұрғын үй сатып алуды ұйымдастыру Ережесі туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49380/rus
