act_code: '37003'
requisite: Решение Маслихата города Астаны от 12 декабря 2007 года № 24/6-IV. Зарегистрировано Департаментом юстиции города Астаны 17 января 2008 года № 481. Утратило силу решением маслихата города Астаны от 28 мая 2009 года № 223/35-IV
title:
  rus: О бюджете города Астаны на 2008 год
  kaz: Астана қаласының 2008 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '151000000002'
version_date:
  kaz: 2007-12-12
  rus: 2007-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/37003/kaz/12.12.2007
  rus: https://zan.gov.kz/client/#!/doc/37003/rus/12.12.2007
