act_code: '37003'
requisite: Решение Маслихата города Астаны от 12 декабря 2007 года № 24/6-IV. Зарегистрировано Департаментом юстиции города Астаны 17 января 2008 года № 481. Утратило силу решением маслихата города Астаны от 28 мая 2009 года № 223/35-IV
title:
  rus: О бюджете города Астаны на 2008 год
  kaz: Астана қаласының 2008 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '151000000002'
version_date:
  kaz: 2008-06-18
  rus: 2008-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/37003/kaz/18.06.2008
  rus: https://zan.gov.kz/client/#!/doc/37003/rus/18.06.2008
caused_by:
  code: '40817'
  requisite: Решение Маслихата города Астаны от 18 июня 2008 года № 110/17-IV. Зарегистрировано Департаментом юстиции города Астаны 16 июля 2008 года № 539. Утратило силу решением маслихата города Астаны от 28 мая 2009 года № 223/35-IV
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 12 декабря 2007 года № 24/6-IV "О бюджете города Астаны на 2008 год"
    kaz: '"Астана қаласының 2008 жылға арналған бюджеті туралы" Астана қаласы мәслихатының 2007 жылғы 12 желтоқсандағы № 24/6-ІV шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/40817/rus
