act_code: '12274'
requisite: Решение Маслихата города Астаны от 2 мая 2002 года N 156/30-II. Зарегистрировано Управлением юстиции города Астаны 25 мая 2002 года N 199. Утратило силу - решением Маслихата города Астаны от 21 сентября 2006 года N 285/35-III
title:
  rus: О Программе по противодействию эпидемии ВИЧ/СПИДа на территории города Астаны на 2002-2005 годы
  kaz: Астана қаласының аумағында ВИЧ/СПИД эпидемиясына қарсы іс-әрекеттер жөніндегі 2002-2005 жылдарға арналған бағдарлама туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2002-05-01
approved_by:
- '151000000002'
version_date:
  kaz: 2002-05-01
  rus: 2002-05-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/12274/kaz/01.05.2002
  rus: https://zan.gov.kz/client/#!/doc/12274/rus/01.05.2002
