act_code: '133024'
requisite: Решение маслихата города Нур-Султана от 27 июня 2019 года № 397/52-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 3 июля 2019 года № 1233. Утратил силу решением маслихата города Нур-Султана от 29 сентября 2021 года № 84/12-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении жителям города Нур-Султан бесплатного проезда на лечение за пределы города за счет бюджетных средств
  kaz: Нұр-Сұлтан қаласының тұрғындарына қала шегінен тыс емделу үшін бюджет қаражаты есебінен тегін жол жүруді ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-27
approved_by:
- '150000000002'
version_date:
  kaz: 2019-06-27
  rus: 2019-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/133024/kaz/27.06.2019
  rus: https://zan.gov.kz/client/#!/doc/133024/rus/27.06.2019
