act_code: '180786'
requisite: Решение маслихата города Астаны от 3 мая 2023 года № 26/3-VIII. Зарегистрировано Департаментом юстиции города Астаны 4 мая 2023 года № 1338-01
title:
  rus: Об оказании в 2023 году дополнительной социальной помощи ветеранам Великой Отечественной войны и другим лицам из числа, не вступивших в повторный брак вдовы воинов, погибших в Великой Отечественной войне в связи с празднованием Дня Победы в Великой Отечественной войне
  kaz: 2023 жылы Ұлы Отан соғысындағы Жеңіс күнін мерекелеуге байланысты Ұлы Отан соғысының ардагерлеріне және басқа адамдарға, атап айтқанда Ұлы Отан соғысында қаза тапқан жауынгердің екінші рет некеге тұрмаған жесірлеріне қосымша әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-03
approved_by:
- '151000000002'
version_date:
  kaz: 2023-05-03
  rus: 2023-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/180786/kaz/03.05.2023
  rus: https://zan.gov.kz/client/#!/doc/180786/rus/03.05.2023
