act_code: '18811'
requisite: Решение Акима города Астаны от 20 февраля 2004 года N 3-1-120. Зарегистрировано Департаментом юстиции города Астаны 2 марта 2004 года N 312. Утратило силу постановлением акимата города Астаны от 9 декабря 2009 года N 06-22
title:
  rus: Об обеспечении лекарственными средствами по видам заболеваний и специализированными продуктами питания отдельных категорий населения города Астаны
  kaz: Астана қаласы тұрғындарының жекелеген санаттарын ауру түрлері бойынша дәрі-дәрмек құралдарымен және мамандандырылған азық-түлікпен қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-02-20
approved_by:
- '151000000001'
version_date:
  kaz: 2004-07-28
  rus: 2004-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/18811/kaz/28.07.2004
  rus: https://zan.gov.kz/client/#!/doc/18811/rus/28.07.2004
caused_by:
  code: '20922'
  requisite: Решение Акима города Астаны от 29 июля 2004 года N 3-1-375. Зарегистрировано Департаментом юстиции города Астаны 17 августа 2004 года N 343. Утратило силу постановлением акимата города Астаны от 9 декабря 2009 года N 06-22
  title:
    rus: О внесении дополнения и изменения в решение акима города Астаны от 20 февраля 2004 года N 3-1-120 "Об обеспечении лекарственными средствами по видам заболеваний и специализированными продуктами питания отдельных категорий населения города Астаны" (регистрационный номер 312)
    kaz: Астана қаласы әкімінің 2004 жылғы 20 ақпандағы N 3-1-120 "Астана қаласы тұрғындарының жекелеген санаттарын ауру түрлері бойынша дәрі-дәрмек құралдарымен және мамандандырылған азық-түлікпен қамтамасыз ету туралы" шешіміне толықтыру мен өзгеріс енгізу туралы (тіркеу нөмірі N 312)
  link: https://zan.gov.kz/client/#!/doc/20922/rus
