act_code: '194783'
requisite: Решение акима Есильского района Акмолинской области от 20 марта 2024 года № 60. Зарегистрировано Департаментом юстиции Акмолинской области 26 марта 2024 года № 8716-03
title:
  rus: Об образовании избирательных участков в Есильском районе
  kaz: Есіл ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-20
approved_by:
- '151000003002'
version_date:
  kaz: 2024-03-20
  rus: 2024-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/194783/kaz/20.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194783/rus/20.03.2024
