act_code: '194783'
requisite: Решение акима Есильского района Акмолинской области от 20 марта 2024 года № 60. Зарегистрировано Департаментом юстиции Акмолинской области 26 марта 2024 года № 8716-03
title:
  rus: Об образовании избирательных участков в Есильском районе
  kaz: Есіл ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-20
approved_by:
- '151000003002'
version_date:
  kaz: 2025-08-29
  rus: 2025-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/194783/kaz/29.08.2025
  rus: https://zan.gov.kz/client/#!/doc/194783/rus/29.08.2025
caused_by:
  code: '214275'
  requisite: Решение акима Есильского района Акмолинской области от 29 августа 2025 года № 4
  title:
    rus: О внесении изменений в решение акима Есильского района от 20 марта 2024 года № 60 «Об образовании избирательных участков в Есильском районе»
    kaz: «Есіл ауданында сайлау учаскелерін құру туралы» Есіл ауданы әкімінің 2024 жылғы 20 наурыздағы № 60 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214275/rus
