act_code: '25238'
requisite: Решение Акима города Астаны от 8 августа 2005 года N 3-1-19. Зарегистрировано в Департаменте юстиции города Астаны 9 сентября 2005 года N 408. Утратило силу постановлением акимата города Астаны от 9 декабря 2009 года N 06-22
title:
  rus: Об утверждении Правил взаимодействия государственных органов по регулированию сбора (заготовки), хранения, переработки и реализации юридическими лицами лома и отходов цветных и черных металлов
  kaz: Заңды тұлғалардың қара және түсті металдардың сынықтары мен қалдықтарын жинау (дайындау), сақтау, қайта өңдеу және сатуды реттеу жөніндегі мемлекеттік органдардың өзара қарым-қатынастары қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-08-08
approved_by:
- '151000000001'
version_date:
  kaz: 2005-08-08
  rus: 2005-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/25238/kaz/08.08.2005
  rus: https://zan.gov.kz/client/#!/doc/25238/rus/08.08.2005
