act_code: '229811'
requisite: Решение маслихата города Астаны от 31 августа 2026 года № 456/58-VIII. Зарегистрировано в Министерстве юстиции Республики Казахстан 8 сентября 2026 года № 39840
title:
  rus: Об утверждении описания и порядка использования региональной символики столицы Республики Казахстан – города Астаны
  kaz: Қазақстан Республикасының елордасы – Астана қаласының өңірлік нышанының сипаттамасын және оны пайдалану тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-31
approved_by:
- '151000000002'
version_date:
  kaz: 2026-08-31
  rus: 2026-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/229811/kaz/31.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229811/rus/31.08.2026
