act_code: '25778'
requisite: Решение маслихата города Астаны от 30 сентября 2005 года N 185/22-III. Зарегистрировано в Департаменте юстиции города Астаны 11 ноября 2005 года N 416. Утратило силу решением маслихата города Астаны от 29 декабря 2010 года № 421/55-IV
title:
  rus: О Программе реконструкции, строительства и технического перевооружения систем водоснабжения и водоотведения города Астаны на 2005-2010 годы
  kaz: 2005-2010 жылдарға арналған Астана қаласын сумен жабдықтау мен су тарту жүйелерін қайта жаңарту, салу және техникалық қайта жабдықтау Бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-09-30
approved_by:
- '151000000002'
version_date:
  kaz: 2009-05-28
  rus: 2009-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/25778/kaz/28.05.2009
  rus: https://zan.gov.kz/client/#!/doc/25778/rus/28.05.2009
caused_by:
  code: '46555'
  requisite: Решение маслихата города Астаны от 28 мая 2009 года № 226/35-IV. Зарегистрировано Департаментом юстиции города Астаны 11 июня 2009 года № 582. Утратило силу решением маслихата города Астаны от 20 июля 2017 года № 166/21-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнений в некоторые решения маслихата города Астаны
    kaz: Астана қаласы мәслихатының кейбір шешімдеріне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/46555/rus
