act_code: '25778'
requisite: Решение маслихата города Астаны от 30 сентября 2005 года N 185/22-III. Зарегистрировано в Департаменте юстиции города Астаны 11 ноября 2005 года N 416. Утратило силу решением маслихата города Астаны от 29 декабря 2010 года № 421/55-IV
title:
  rus: О Программе реконструкции, строительства и технического перевооружения систем водоснабжения и водоотведения города Астаны на 2005-2010 годы
  kaz: 2005-2010 жылдарға арналған Астана қаласын сумен жабдықтау мен су тарту жүйелерін қайта жаңарту, салу және техникалық қайта жабдықтау Бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-09-30
approved_by:
- '151000000002'
version_date:
  kaz: 2005-09-30
  rus: 2005-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/25778/kaz/30.09.2005
  rus: https://zan.gov.kz/client/#!/doc/25778/rus/30.09.2005
