act_code: '52588'
requisite: Решение маслихата города Астаны от 21 апреля 2010 года N 344/46-IV. Зарегистрировано Департаментом юстиции города Астаны 21 мая 2010 года N 631. Утратило силу решением маслихата города Астаны от 3 марта 2011 года № 435/58-IV
title:
  rus: О Правилах оказания дополнительной социальной помощи отдельным категориям граждан города Астаны в связи с празднованием 65-ой годовщины Победы в Великой Отечественной войне 1941-1945 годов
  kaz: 1941-1945 жылдардағы Ұлы Отан соғысы Жеңісінің 65 жылдығын мерекелеуге байланысты Астана қаласы азаматтарының жекелеген санаттарына қосымша әлеуметтік көмек көрсету Ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-04-21
approved_by:
- '151000000002'
version_date:
  kaz: 2010-07-29
  rus: 2010-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/52588/kaz/29.07.2010
  rus: https://zan.gov.kz/client/#!/doc/52588/rus/29.07.2010
caused_by:
  code: '54259'
  requisite: Решение маслихата города Астаны от 29 июля 2010 года N 381/50-IV. Зарегистрировано Департаментом юстиции города Астаны 31 августа 2010 года N 646. Утратило силу решением маслихата города Астаны от 3 марта 2011 года № 435/58-IV
  title:
    rus: О внесении изменения и дополнения в решение маслихата города Астаны от 21 апреля 2010 года № 344/46-IV "О Правилах оказания дополнительной социальной помощи отдельным категориям граждан города Астаны в связи с празднованием 65-ой годовщины Победы в Великой Отечественной войне 1941-1945 годов"
    kaz: Астана қаласы мәслихатының 2010 жылғы 21 сәуірдегі № 344/46-ІV «1941-1945 жылдардағы Ұлы Отан соғысы Жеңісінің 65 жылдығын мерекелеуге байланысты Астана қаласы азаматтарының жекелеген санаттарына қосымша әлеуметтік көмек көрсету ережесі туралы» шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/54259/rus
