act_code: '117372'
requisite: Решение маслихата города Астаны от 12 декабря 2017 года № 214/25-VI. Зарегистрировано Департаментом юстиции города Астаны 28 декабря 2017 года № 1148
title:
  rus: О бюджете города Астаны на 2018-2020 годы
  kaz: Астана қаласының 2018-2020 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2017-12-12
approved_by:
- '151000000002'
version_date:
  kaz: 2018-06-06
  rus: 2018-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/117372/kaz/06.06.2018
  rus: https://zan.gov.kz/client/#!/doc/117372/rus/06.06.2018
caused_by:
  code: '122855'
  requisite: Решение маслихата города Астаны от 6 июня 2018 года № 272/33-VI. Зарегистрировано Департаментом юстиции города Астаны 22 июня 2018 года № 1180
  title:
    rus: О внесении изменений и дополнения в решение маслихата города Астаны от 12 декабря 2017 года № 214/25-VI «О бюджете города Астаны на 2018-2020 годы»
    kaz: «Астана қаласының 2018-2020 жылдарға арналған бюджеті туралы» Астана қаласы мәслихатының 2017 жылғы 12 желтоқсандағы № 214/25-VI шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122855/rus
