act_code: '117372'
requisite: Решение маслихата города Астаны от 12 декабря 2017 года № 214/25-VI. Зарегистрировано Департаментом юстиции города Астаны 28 декабря 2017 года № 1148
title:
  rus: О бюджете города Астаны на 2018-2020 годы
  kaz: Астана қаласының 2018-2020 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2017-12-12
approved_by:
- '151000000002'
version_date:
  kaz: 2017-12-12
  rus: 2017-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/117372/kaz/12.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117372/rus/12.12.2017
