act_code: '75638'
requisite: Решение маслихата города Астаны от 29 ноября 2013 года № 193/27-V. Зарегистрировано Департаментом юстиции города Астаны 29 ноября 2013 года № 792. Утратило силу решением маслихата города Астаны от 27 марта 2014 года № 226/31-V
title:
  rus: О Правилах оказания единовременной социальной помощи отдельным категориям нуждающихся граждан города Астаны ко Дню Первого Президента Республики Казахстан
  kaz: Қазақстан Республикасының Тұңғыш Президенті күніне орай Астана қаласындағы мұқтаж азаматтардың жекелеген санаттарына біржолғы әлеуметтiк көмек көрсету ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-11-29
approved_by:
- '151000000002'
version_date:
  kaz: 2013-11-29
  rus: 2013-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/75638/kaz/29.11.2013
  rus: https://zan.gov.kz/client/#!/doc/75638/rus/29.11.2013
