act_code: '15376'
requisite: Решение Маслихата города Астаны от 8 апреля 2003 года N 224/42-II. Зарегистрировано Управлением юстиции города Астаны от 16 мая 2003 года N 267. Утратило силу - решением Маслихата города Астаны от 21 сентября 2006 года N 285/35-III
title:
  rus: О Региональной программе демографического развития на 2003-2005 годы
  kaz: 2003-2005 жылдар кезеңіне арналған демографиялық дамытудың аймақтық бағдарламасы туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2003-04-07
approved_by:
- '151000000002'
version_date:
  kaz: 2003-04-07
  rus: 2003-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/15376/kaz/07.04.2003
  rus: https://zan.gov.kz/client/#!/doc/15376/rus/07.04.2003
