act_code: '16662'
requisite: Решение маслихата города Астаны от 12 августа 2003 года N 253/49-II. Зарегистрировано Управлением юстиции города Астаны от 19 августа 2003 года N 287. Утратило силу - решением Маслихата города Астаны от 14 декабря 2006 года N 326/40-III
title:
  rus: О Программе борьбы с коррупцией по городу Астане на 2003-2005 годы
  kaz: Астана қаласы бойынша сыбайлас жемқорлықпен күресу жөніндегі 2003-2005 жылдарға арналған бағдарлама туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2003-08-11
approved_by:
- '151000000002'
version_date:
  kaz: 2003-08-11
  rus: 2003-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/16662/kaz/11.08.2003
  rus: https://zan.gov.kz/client/#!/doc/16662/rus/11.08.2003
