act_code: '11561'
requisite: Решение Маслихата города Астаны от 5 марта 2002 года N 149/29-II. Зарегистрировано управлением юстиции г.Астаны от 18 марта 2002 года N 178. Утратило силу решением Маслихата города Астаны от 18 августа 2008 года N 137/21-IV
title:
  rus: Об установлении ставок платы за размещение наружной (визуальной) рекламы
  kaz: Сыртқы (көрнекі) жарнама орнатқаны үшін ақы ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-03-05
approved_by:
- '151000000002'
version_date:
  kaz: 2002-03-05
  rus: 2002-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/11561/kaz/05.03.2002
  rus: https://zan.gov.kz/client/#!/doc/11561/rus/05.03.2002
