act_code: '114140'
requisite: Решение маслихата города Астаны от 20 июля 2017 года № 167/21-VI. Зарегистрировано Департаментом юстиции города Астаны 15 августа 2017 года № 1124
title:
  rus: О порядке оказания социальной помощи отдельным категориям граждан города Астаны в виде освобождения от оплаты за проезд на маршрутах городского пассажирского транспорта
  kaz: Астана қаласы азаматтарының жекелеген санаттарына қалалық бағдарлардың жолаушылар көлігінде жол жүруге төлем төлеуден босату түрінде әлеуметтік көмек көрсету тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-07-20
approved_by:
- '151000000002'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/114140/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/114140/rus/29.03.2024
caused_by:
  code: '195460'
  requisite: Решение маслихата города Астаны от 29 марта 2024 года № 159/20-VIII. Зарегистрировано Департаментом юстиции города Астаны 9 апреля 2024 года № 1378-01
  title:
    rus: О внесении изменения в решение маслихата города Астаны от 20 июля 2017 года № 167/21-VI «О порядке оказания социальной помощи отдельным категориям граждан города Астаны в виде освобождения от оплаты за проезд на маршрутах городского пассажирского транспорта»
    kaz: «Астана қаласы азаматтарының жекелеген санаттарына қалалық бағдарлардың жолаушылар көлігінде жол жүруге төлем төлеуден босату түрінде әлеуметтік көмек көрсету тәртібі туралы» Астана қаласы мәслихатының 2017 жылғы 20 шілдедегі № 167/21-VI шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195460/rus
