act_code: '108789'
requisite: Решение маслихата города Астаны от 8 декабря 2016 года № 86/13-VI. Зарегистрировано Департаментом юстиции города Астаны 28 декабря 2016 года № 1087. Утратило силу решением маслихата города Астаны от 23 июня 2017 года № 161/20-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О Правилах оказания единовременной социальной помощи жертвам политических репрессий из числа участников событий 17-18 декабря 1986 года в Казахстане к 25-летию Независимости Республики Казахстан
  kaz: Қазақстан Республикасы Тәуелсiздiгінің 25 жылдығына орай Қазақстандағы 1986 жылғы 17-18 желтоқсан оқиғаларына қатысушылар қатарындағы саяси қуғын-сүргін құрбандарына біржолғы әлеуметтік көмек көрсету қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-08
approved_by:
- '151000000002'
version_date:
  kaz: 2016-12-08
  rus: 2016-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/108789/kaz/08.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108789/rus/08.12.2016
