act_code: '21601'
requisite: Решение Акима города Астаны от 21 сентября 2004 года N 3-1-381. Зарегистрировано Департаментом юстиции города Астаны 20 октября 2004 года N 356. Утратило силу постановлением акимата города Астаны от 9 декабря 2009 года N 06-22
title:
  rus: О проведении начальной военной подготовки молодежи в учебных заведениях города Астана в 2004-2005 учебном году
  kaz: 2004-2005 оқу жылында Астана қаласының оқу орындарында жастардың бастапқы әскери даярлығын өткізу туралы
form: РЕШ
type_codes:
- ПЛАН
- ПРОГ
- РЕШ
approved_on: 2004-09-20
approved_by:
- '151000000001'
version_date:
  kaz: 2004-09-20
  rus: 2004-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/21601/kaz/20.09.2004
  rus: https://zan.gov.kz/client/#!/doc/21601/rus/20.09.2004
