act_code: '21736'
requisite: Решение Маслихата города Астаны от 30 сентября 2004 года N 81/12-III. Зарегистрировано Департаментом юстиции города Астаны 4 ноября 2004 года N 359. Утратило силу - решением Маслихата города Астаны от 14 декабря 2006 года N 306/40-III
title:
  rus: О Программе индустриально-инновационного развития города Астаны на 2004-2006 годы
  kaz: Астана қаласының 2004-2006 жылдарға арналған индустриалдық-инновациялық даму бағдарламасы туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2004-09-29
approved_by:
- '151000000002'
version_date:
  kaz: 2004-09-29
  rus: 2004-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/21736/kaz/29.09.2004
  rus: https://zan.gov.kz/client/#!/doc/21736/rus/29.09.2004
