act_code: '24592'
requisite: "Решение Маслихата города Астаны от 7 июня 2005 года N 154/19-III.\r\nЗарегистрировано в Департаменте юстиции города Астаны 4 июля 2005 года N 398. Утратило силу решением маслихата города Астаны от 31 марта 2009 года N 203/31-IV"
title:
  rus: Об установлении ставок фиксированного суммарного налога
  kaz: Тіркелген жиынтық салығының ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-06-07
approved_by:
- '151000000002'
version_date:
  kaz: 2005-06-07
  rus: 2005-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/24592/kaz/07.06.2005
  rus: https://zan.gov.kz/client/#!/doc/24592/rus/07.06.2005
