act_code: '16472'
requisite: Решение маслихата города Астаны от 4 июля 2003 года N 246/47-II. Зарегистрировано Управлением юстиции города Астаны 30 июля 2003 года N 283. Утратило силу решением маслихата города Астаны от 22 сентября 2010 года N 387/51-IV
title:
  rus: О Правилах предоставления жилищной помощи на оплату за содержание жилища, потребленные коммунальные услуги и услуги связи в городе Астане
  kaz: Астана қаласында тұрғын үйді ұстауға, тұтынылған коммуналдық қызметтерге және байланыс қызметтеріне ақы төлеуге тұрғын үй көмегін беру ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-07-03
approved_by:
- '151000000002'
version_date:
  kaz: 2009-05-28
  rus: 2009-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/16472/kaz/28.05.2009
  rus: https://zan.gov.kz/client/#!/doc/16472/rus/28.05.2009
caused_by:
  code: '46555'
  requisite: Решение маслихата города Астаны от 28 мая 2009 года № 226/35-IV. Зарегистрировано Департаментом юстиции города Астаны 11 июня 2009 года № 582. Утратило силу решением маслихата города Астаны от 20 июля 2017 года № 166/21-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнений в некоторые решения маслихата города Астаны
    kaz: Астана қаласы мәслихатының кейбір шешімдеріне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/46555/rus
