act_code: '16472'
requisite: Решение маслихата города Астаны от 4 июля 2003 года N 246/47-II. Зарегистрировано Управлением юстиции города Астаны 30 июля 2003 года N 283. Утратило силу решением маслихата города Астаны от 22 сентября 2010 года N 387/51-IV
title:
  rus: О Правилах предоставления жилищной помощи на оплату за содержание жилища, потребленные коммунальные услуги и услуги связи в городе Астане
  kaz: Астана қаласында тұрғын үйді ұстауға, тұтынылған коммуналдық қызметтерге және байланыс қызметтеріне ақы төлеуге тұрғын үй көмегін беру ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-07-03
approved_by:
- '151000000002'
version_date:
  kaz: 2005-02-17
  rus: 2005-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/16472/kaz/17.02.2005
  rus: https://zan.gov.kz/client/#!/doc/16472/rus/17.02.2005
caused_by:
  code: '23147'
  requisite: Решение Маслихата города Астаны от 17 февраля 2005 года N 119/16-III. Зарегистрировано Департаментом юстиции города Астаны 14 марта 2005 года N 379. Утратило силу решением маслихата города Астаны от 22 сентября 2010 года N 387/51-IV
  title:
    rus: О внесении изменений и дополнений в решение маслихата города Астаны от 4 июля 2003 года N 246/47-II "О Правилах предоставления жилищного пособия на оплату за содержание жилища и потребленные коммунальные услуги в городе Астане" (зарегистрировано Департаментом юстиции города Астаны 30 июля 2003 года за N 283)
    kaz: '"Астана қаласында тұрғын үйді ұстауға және тұтынылған коммуналдық қызметтерге ақы төлеуге тұрғын үй жәрдемақысын беру ережесі туралы" Астана қаласы мәслихатының 2003 жылғы 4 шілдедегі N 246/47-ІІ шешіміне (Астана қаласының әділет департаментінде 2003 жылғы 30 шілдеде N 283 тіркелген) өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/23147/rus
