act_code: '16472'
requisite: Решение маслихата города Астаны от 4 июля 2003 года N 246/47-II. Зарегистрировано Управлением юстиции города Астаны 30 июля 2003 года N 283. Утратило силу решением маслихата города Астаны от 22 сентября 2010 года N 387/51-IV
title:
  rus: О Правилах предоставления жилищной помощи на оплату за содержание жилища, потребленные коммунальные услуги и услуги связи в городе Астане
  kaz: Астана қаласында тұрғын үйді ұстауға, тұтынылған коммуналдық қызметтерге және байланыс қызметтеріне ақы төлеуге тұрғын үй көмегін беру ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-07-03
approved_by:
- '151000000002'
version_date:
  kaz: 2007-07-12
  rus: 2007-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/16472/kaz/12.07.2007
  rus: https://zan.gov.kz/client/#!/doc/16472/rus/12.07.2007
caused_by:
  code: '34373'
  requisite: Решение маслихата города Астаны от 12 июля 2007 года N 398/50-III. Зарегистрировано в Департаменте юстиции города Астаны 30 июля 2007 года N 475. Утратило силу решением маслихата города Астаны от 22 сентября 2010 года N 387/51-IV
  title:
    rus: О внесении изменений и дополнений в решение маслихата города Астаны от 04 июля 2003 года N 246/47-II "О Правилах предоставления жилищного пособия на оплату за содержание жилища, потребленные коммунальные услуги и услуги связи в городе Астане"
    kaz: Астана қаласы мәслихатының 2003 жылғы 04 шілдедегі N 246/47-11»"Астана қаласында тұрғын үйді ұстауға және тұтынылған коммуналдық қызметтерге және байланыс қызметтеріне ақы төлеу үшін тұрғын үй жәрдемақысын беру Қағидалары туралы" шешіміне өзгерістер және толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/34373/rus
