act_code: '28459'
requisite: Решение Маслихата города Астаны от 7 июня 2006 года N 253/32-III. Зарегистрировано в Департаменте юстиции г. Астаны от 23 июня 2006 года N 442. Утратило силу решением маслихата города Астаны от 23 сентября 2015 года № 410/57-V
title:
  rus: О льготном проезде обучающихся на общественном транспорте
  kaz: Қоғамдық көлікте білім алушылардың жеңілдікпен жүруі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-06-07
approved_by:
- '151000000002'
version_date:
  kaz: 2006-06-07
  rus: 2006-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/28459/kaz/07.06.2006
  rus: https://zan.gov.kz/client/#!/doc/28459/rus/07.06.2006
