act_code: '223953'
requisite: Решение маслихата города Астаны от 19 марта 2026 года № 394/51-VIII
title:
  rus: Об определении размера платы за доставление (эвакуацию) транспортных средств и их временное хранение на специальных площадках, стоянках, находящихся в коммунальной собственности города Астаны
  kaz: Астана қаласының коммуналдық меншігіндегі арнаулы алаңдарға, тұрақтарға көлік құралдарын жеткізгені (эвакуациялағаны) және  уақытша сақтағаны үшін төлемақы мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-03-19
approved_by:
- '151000000002'
version_date:
  kaz: 2026-03-19
  rus: 2026-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/223953/kaz/19.03.2026
  rus: https://zan.gov.kz/client/#!/doc/223953/rus/19.03.2026
