act_code: '66184'
requisite: Решение маслихата города Астаны от 6 июня 2012 года № 27/4-V. Зарегистрировано Департаментом юстиции города Астаны 19 июня 2012 года № 728. Утратило силу решением маслихата города Астаны от 19 июня 2024 года № 185/23-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня социально значимых сообщений города Астаны
  kaz: Астана қаласының әлеуметтік маңызды қатынастарының тізбесін бекіту туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2012-06-06
approved_by:
- '151000000002'
version_date:
  kaz: 2014-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/66184/kaz/28.05.2014
caused_by:
  code: '80993'
  requisite: Решение маслихата города Астаны от 28 мая 2014 года № 242/34-V. Зарегистрировано Департаментом юстиции города Астаны 19 июня 2014 года № 815
  title:
    rus: О внесении дополнения в решение маслихата города Астаны от 6 июня 2012 года № 27/4-V "Об утверждении перечня социально значимых сообщений города Астаны"
    kaz: Астана қаласы мәслихатының 2012 жылғы 6 маусымдағы № 27/4-V "Астана қаласының әлеуметтік маңызды қатынастарының тізбесін бекіту туралы" шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/80993/rus
