act_code: '66184'
requisite: Решение маслихата города Астаны от 6 июня 2012 года № 27/4-V. Зарегистрировано Департаментом юстиции города Астаны 19 июня 2012 года № 728. Утратило силу решением маслихата города Астаны от 19 июня 2024 года № 185/23-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня социально значимых сообщений города Астаны
  kaz: Астана қаласының әлеуметтік маңызды қатынастарының тізбесін бекіту туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2012-06-06
approved_by:
- '151000000002'
version_date:
  kaz: 2016-06-03
  rus: 2016-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/66184/kaz/03.06.2016
  rus: https://zan.gov.kz/client/#!/doc/66184/rus/03.06.2016
caused_by:
  code: '104529'
  requisite: Решение маслихата города Астаны от 3 июня 2016 года № 22/5-VI. Зарегистрировано Департаментом юстиции города Астаны 30 июня 2016 года № 1037. Утратило силу решением маслихата города Астаны от 19 июня 2024 года № 185/23-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата города Астаны от 6 июня 2012 года № 27/4-V «Об утверждении перечня социально  значимых сообщений города Астаны»
    kaz: «Астана қаласының әлеуметтік маңызды қатынастарының тізбесін бекіту туралы» Астана қаласы мәслихатының 2012 жылғы 6 маусымдағы № 27/4-V шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104529/rus
