act_code: '66184'
requisite: Решение маслихата города Астаны от 6 июня 2012 года № 27/4-V. Зарегистрировано Департаментом юстиции города Астаны 19 июня 2012 года № 728. Утратило силу решением маслихата города Астаны от 19 июня 2024 года № 185/23-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня социально значимых сообщений города Астаны
  kaz: Астана қаласының әлеуметтік маңызды қатынастарының тізбесін бекіту туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2012-06-06
approved_by:
- '151000000002'
version_date:
  kaz: 2014-12-11
  rus: 2014-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/66184/kaz/11.12.2014
  rus: https://zan.gov.kz/client/#!/doc/66184/rus/11.12.2014
caused_by:
  code: '86041'
  requisite: Решение маслихата города Астаны от 11 декабря 2014 года № 310/45-V. Зарегистрировано Департаментом юстиции города Астаны 12 января 2015 года № 873. Утратило силу решением маслихата города Астаны от 19 июня 2024 года № 185/23-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата города Астаны от 6 июня 2012 года № 27/4-V «Об утверждении перечня социально значимых сообщений города Астаны»
    kaz: «Астана қаласының әлеуметтік маңызды қатынастарының тізбесін бекіту туралы» Астана қаласы мәслихатының 2012 жылғы 6 маусымдағы № 27/4-V шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86041/rus
