act_code: '129845'
requisite: Решение маслихата города Астаны от 6 марта 2019 года № 356/45-VI. Зарегистрировано Департаментом юстиции города Астаны 27 марта 2019 года № 1210. Утратило силу решением маслихата города Астаны от 7 марта 2024 года № 152/19-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил регулирования миграционных процессов в городе Астане
  kaz: Астана қаласының көші-қон процестерін реттеу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-03-06
approved_by:
- '151000000002'
version_date:
  kaz: 2021-11-24
  rus: 2021-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/129845/kaz/24.11.2021
  rus: https://zan.gov.kz/client/#!/doc/129845/rus/24.11.2021
caused_by:
  code: '160850'
  requisite: Решение маслихата города Нур-Султана от 24 ноября 2021 года № 106/15-VII. Утратило силу решением маслихата города Астаны от 7 марта 2024 года № 149/19-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 6 марта 2019 года № 356/45-VI «Об утверждении правил регулирования миграционных процессов в городе Астане»
    kaz: «Астана қаласының көші-қон процестерін реттеу қағидаларын бекіту туралы» Астана қаласы мәслихатының 2019 жылғы 6 наурыздағы № 356/45-VI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160850/rus
