act_code: '129845'
requisite: Решение маслихата города Астаны от 6 марта 2019 года № 356/45-VI. Зарегистрировано Департаментом юстиции города Астаны 27 марта 2019 года № 1210. Утратило силу решением маслихата города Астаны от 7 марта 2024 года № 152/19-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил регулирования миграционных процессов в городе Астане
  kaz: Астана қаласының көші-қон процестерін реттеу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-03-06
approved_by:
- '151000000002'
version_date:
  kaz: 2019-03-06
  rus: 2019-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/129845/kaz/06.03.2019
  rus: https://zan.gov.kz/client/#!/doc/129845/rus/06.03.2019
