act_code: '220866'
requisite: Решение маслихата города Астаны от 26 декабря 2025 года № 368/48-VIII. Утратило силу решением маслихата города Астаны от 14 августа 2026 года № 452/58-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норматива регистрации по месту жительства и месту временного пребывания (проживания) на территории города Астаны
  kaz: Астана қаласының аумағында тұрғылықты жері және уақытша болу (тұру) орны бойынша тіркеу нормативін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '151000000002'
version_date:
  kaz: 2025-12-26
  rus: 2025-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/220866/kaz/26.12.2025
  rus: https://zan.gov.kz/client/#!/doc/220866/rus/26.12.2025
