act_code: '217031'
requisite: Решение маслихата города Астаны от 12 ноября 2025 года № 339/45-VIII
title:
  rus: Об утверждении Правил общего водопользования в городе Астане
  kaz: Астана қаласында ортақ су пайдалану қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2025-11-12
approved_by:
- '151000000002'
version_date:
  kaz: 2025-11-12
  rus: 2025-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/217031/kaz/12.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217031/rus/12.11.2025
