act_code: '201463'
requisite: Решение акима города Астаны от 4 октября 2024 года № 502-18. Зарегистрировано Департаментом юстиции города Астаны 8 октября 2024 года № 1396-01
title:
  rus: Об определении порядка реализации продукции в стеклянной таре в местах проведения спортивно-массовых, зрелищных культурно-массовых мероприятий в городе Астане
  kaz: Астана қаласында спорттық-бұқаралық, ойын-сауық, мәдени-бұқаралық іс-шаралар өткізілетін орындарда шыны ыдыстағы өнімдерді сату тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-10-04
approved_by:
- '151000000003'
version_date:
  kaz: 2024-10-04
  rus: 2024-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/201463/kaz/04.10.2024
  rus: https://zan.gov.kz/client/#!/doc/201463/rus/04.10.2024
