act_code: '81611'
requisite: Решение маслихата города Астаны от 27 июня 2014 года № 250/36-V. Зарегистрировано Департаментом юстиции города Астаны 23 июля 2014 года № 822. Утратило силу решением маслихата города Астаны от 12 декабря 2017 года № 221/25-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О Правилах оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Астаны
  kaz: Астана қаласында әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-06-27
approved_by:
- '151000000002'
version_date:
  kaz: 2016-06-24
  rus: 2016-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/81611/kaz/24.06.2016
  rus: https://zan.gov.kz/client/#!/doc/81611/rus/24.06.2016
caused_by:
  code: '105142'
  requisite: Решение маслихата города Астаны от 24 июня 2016 года № 34/7-VI. Зарегистрировано Департаментом юстиции города Астаны 15 июля 2016 года № 1039. Утратило силу решением маслихата города Астаны от 12 декабря 2017 года № 221/25-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 27 июня 2014 года № 250/36-V «О Правилах оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Астаны»
    kaz: «Астана қаласында әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидасы туралы» Астана қаласы мәслихатының 2014 жылғы 27 маусымдағы № 250/36-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/105142/rus
