act_code: '208654'
requisite: Решение маслихата города Астаны от 18 марта 2025 года № 283/35-VIII
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов в городе Астане
  kaz: Астана қаласында коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2025-03-18
approved_by:
- '151000000002'
version_date:
  kaz: 2025-03-18
  rus: 2025-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/208654/kaz/18.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208654/rus/18.03.2025
