act_code: '195494'
requisite: Решение маслихата города Астаны от 29 марта 2024 года № 162/20-VIII. Отменено решением маслихата города Астаны от 25 сентября 2024 года № 221/27-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном предоставлении гарантированного объема бесплатной медицинской помощи, в том числе лекарственных средств, специализированных лечебных продуктов, медицинских изделий, отдельным категориям граждан Республики Казахстан, зарегистрированным в городе Астане при амбулаторном лечении бесплатно
  kaz: Астана қаласында тіркелген Қазақстан Республикасы азаматтарының жекелеген санаттарына амбулаториялық емдеу кезінде тегін медициналық көмектің кепілдік берілген көлемін, оның ішінде дәрілік заттарды, бейімделген емдік өнімдерді, медициналық бұйымдарды қосымша тегін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-29
approved_by:
- '151000000002'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/195494/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195494/rus/29.03.2024
