act_code: '101802'
requisite: Решение маслихата города Астаны от 15 апреля 2016 года № 7/2-VI. Зарегистрировано Департаментом юстиции города Астаны 27 апреля 2016 года № 1012. Утратило силу решением маслихата города Астаны от 24 июня 2016 года № 35/7-VI
title:
  rus: Об оказании  дополнительной социальной помощи отдельным категориям граждан города Астаны
  kaz: Астана қаласының жекелеген санаттағы азаматтарына қосымша  әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-15
approved_by:
- '151000000002'
version_date:
  kaz: 2016-04-15
  rus: 2016-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/101802/kaz/15.04.2016
  rus: https://zan.gov.kz/client/#!/doc/101802/rus/15.04.2016
