act_code: '133025'
requisite: Решение маслихата города Нур-Султана от 27 июня 2019 года № 396/52-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 3 июля 2019 года № 1234. Утратило силу решением маслихата города Нур-Султана от 2 июня 2020 года № 500/66-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном предоставлении лекарственных средств, специализированных лечебных продуктов, медицинских изделий отдельным категориям граждан при амбулаторном лечении бесплатно и на льготных условиях
  kaz: Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін және жеңілдікті шарттармен дәрілік заттарды, бейімделген емдік өнімдерді, медициналық бұйымдарды косымша беру туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2019-06-27
approved_by:
- '150000000002'
version_date:
  kaz: 2019-06-27
  rus: 2019-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/133025/kaz/27.06.2019
  rus: https://zan.gov.kz/client/#!/doc/133025/rus/27.06.2019
