act_code: '24590'
requisite: Решение Маслихата города Астана от 26 мая 2005 года N 141/18-ІІІ. Зарегистрировано в Департаменте юстиции города Астаны 1 июля 2005 года N 396. Утратило силу решением маслихата города Астаны от 29 июля 2010 года N 380/50-V
title:
  rus: О Региональной программе развития промышленности строительных материалов, изделий и конструкций в городе Астане на 2005-2014 годы
  kaz: Астана қаласында құрылыс материалдары, бұйымдар мен құрылымдар өнеркәсібі дамуының 2005-2014 жылдарға арналған аймақтық бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2005-05-26
approved_by:
- '151000000002'
version_date:
  kaz: 2005-05-26
  rus: 2005-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/24590/kaz/26.05.2005
  rus: https://zan.gov.kz/client/#!/doc/24590/rus/26.05.2005
