act_code: '12312'
requisite: Решение маслихата города Астаны от 2 мая 2002 года N 161/30-II. Зарегистрировано управлением юстиции города Астаны 5 июня 2002 года N 206. Утратило силу решением маслихата города Астаны от 24 сентября 2013 года № 175/23-V
title:
  rus: О дополнительном регламентировании порядка и мест для проведения мирных собраний, митингов и пикетов
  kaz: Бейбіт жиналыстар, митингілер және пикеттер өткізудің тәртібі мен орнын қосымша регламенттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-05-01
approved_by:
- '151000000002'
version_date:
  kaz: 2010-05-28
  rus: 2010-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/12312/kaz/28.05.2010
  rus: https://zan.gov.kz/client/#!/doc/12312/rus/28.05.2010
caused_by:
  code: '53419'
  requisite: Решение маслихата города Астаны от 28 мая 2010 года № 358/48-IV. Зарегистрировано Департаментом юстиции города Астаны 2 июля 2010 года № 635. Утратило силу решением маслихата города Астаны от 24 сентября 2013 года № 175/23-V
  title:
    rus: О внесении изменения в решение маслихата города Астаны от 2 мая 2002 года № 161/30-II "О дополнительном регламентировании порядка и мест для проведения мирных собраний, митингов и пикетов"
    kaz: '"Бейбіт жиналыстар, митингілер және пикеттер өткізудің тәртібі мен орнын қосымша регламенттеу туралы" Астана қаласы мәслихатының 2002 жылғы 2 мамырдағы N 161/30-ІІ шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/53419/rus
