act_code: '175947'
requisite: Решение маслихата города Астаны от 14 декабря 2022 года № 274/36-VII
title:
  rus: О бюджете города Астаны на 2023-2025 годы
  kaz: Астана қаласының 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-14
approved_by:
- '151000000002'
version_date:
  kaz: 2023-04-12
  rus: 2023-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/175947/kaz/12.04.2023
  rus: https://zan.gov.kz/client/#!/doc/175947/rus/12.04.2023
caused_by:
  code: '180170'
  requisite: Решение маслихата города Астаны от 12 апреля 2023 года № 13/2-VII
  title:
    rus: О внесении изменений и дополнений в решение маслихата города Астаны от 14 декабря 2022 года № 274/36-VII «О бюджете города Астаны на 2023-2025 годы»
    kaz: Астана қаласы мәслихатының 2022 жылғы 14 желтоқсандағы № 274/36-VII «Астана қаласының 2023-2025 жылдарға арналған бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180170/rus
