act_code: '97679'
requisite: Решение от 11.12.2015 № 428/61-V, Маслихат г. Астаны. Зарегистрировано Департаментом юстиции города Астаны 12 января 2016 года № 990
title:
  rus: О бюджете города Астаны на 2016-2018 годы
  kaz: 'Астана қаласының 2016-2018 жылдарға арналған бюджеті туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-11
approved_by:
- '151000000002'
version_date:
  kaz: 2016-11-29
  rus: 2016-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/97679/kaz/29.11.2016
  rus: https://zan.gov.kz/client/#!/doc/97679/rus/29.11.2016
caused_by:
  code: '108791'
  requisite: Решение маслихата города Астаны от 29 ноября 2016 года № 80/12-VI. Зарегистрировано Департаментом юстиции города Астаны 13 декабря 2016 года № 1081
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 11 декабря 2015 года № 428/61-V «О бюджете города Астаны на 2016-2018 годы»
    kaz: «Астана қаласының 2016-2018 жылдарға арналған бюджеті туралы» Астана қаласы мәслихатының 2015 жылғы 11 желтоқсандағы № 428/61-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108791/rus
