act_code: '107897'
requisite: Решение маслихата города Астаны от 26 мая 2016 года № 12/4-VI
title:
  rus: Об утверждении отчета об исполнении бюджета города Астаны за 2015 год
  kaz: Астана қаласының 2015 жылғы бюджетінің атқарылуы туралы есебін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-26
approved_by:
- '151000000002'
version_date:
  kaz: 2016-05-26
  rus: 2016-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/107897/kaz/26.05.2016
  rus: https://zan.gov.kz/client/#!/doc/107897/rus/26.05.2016
