act_code: '24546'
requisite: "Решение Маслихата города Астаны от 26 мая 2005 года N 142/18-III.\r\nЗарегистрировано Департаментом юстиции города Астаны 1 июля 2005 года N 394. Утратило силу решением Маслихата города Астаны от 17 октября 2007 года N 16/4-IV"
title:
  rus: О Правилах оказания социальной помощи к праздничным и знаменательным датам отдельным категориям граждан
  kaz: Азаматтардың жекелеген санаттарына мерекелiк және айтулы күндерге әлеуметтiк көмек көрсету қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-05-26
approved_by:
- '151000000002'
version_date:
  kaz: 2005-05-26
  rus: 2005-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/24546/kaz/26.05.2005
  rus: https://zan.gov.kz/client/#!/doc/24546/rus/26.05.2005
