act_code: '22351'
requisite: Решение Маслихата города Астаны от 24 декабря 2004 года N 104/15-III. Зарегистрировано Департаментом юстиции города Астаны 29 декабря 2004 года N 367. Утратило силу - решением Маслихата города Астаны от 21 сентября 2006 года N 285/35-III
title:
  rus: О бюджете города Астаны на 2005 год
  kaz: Астана қаласының 2005 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-24
approved_by:
- '151000000002'
version_date:
  kaz: 2005-11-17
  rus: 2005-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/22351/kaz/17.11.2005
  rus: https://zan.gov.kz/client/#!/doc/22351/rus/17.11.2005
caused_by:
  code: '25962'
  requisite: Решение Маслихата города Астаны от 17 ноября 2005 года N 196/23-III. Зарегистрировано Департаментом юстиции города Астаны 2 декабря 2005 года за N 421. Утратило силу - решением Маслихата города Астаны от 21 сентября 2006 года N 285/35-III
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 24 декабря 2004 года N 104/15-III "О бюджете города Астаны на 2005 год" (зарегистрировано Департаментом юстиции города Астаны 29 декабря 2004 года за N 367)
    kaz: Астана қаласы мәслихатының 2004 жылғы 24 желтоқсандағы N 104/15-III "Астана қаласының 2005 жылға арналған бюджеті туралы" (2004 жылдың 29 желтоқсанында Астана қаласының Әділет департаментінде N 367 болып тіркелген) шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/25962/rus
