act_code: '29026'
requisite: Решение Маслихата города Астаны от 7 июня 2006 года N 252/32-III. Зарегистрировано в Департаменте юстиции города Астаны от 27 июля 2006 года N 447. Утратило силу решением маслихата города Астаны от 3 марта 2011 года № 432/58-IV
title:
  rus: О Правилах застройки территории города Астаны
  kaz: Астана қаласының аумағында құрылыс салу Қағидалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-06-07
approved_by:
- '151000000002'
version_date:
  kaz: 2010-05-28
  rus: 2010-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/29026/kaz/28.05.2010
  rus: https://zan.gov.kz/client/#!/doc/29026/rus/28.05.2010
caused_by:
  code: '53300'
  requisite: Решение маслихата города Астаны от 28 мая 2010 года № 355/48-IV. Зарегистрировано Департаментом юстиции города Астаны 24 июня 2010 года № 634. Утратило силу решением маслихата города Астаны от 3 марта 2011 года № 432/58-IV
  title:
    rus: О внесении дополнений в решение маслихата города Астаны от 7 июня 2006 года № 252/32-III "О Правилах застройки территории города Астаны"
    kaz: Астана қаласы мәслихатының 2006 жылғы 7 маусымдағы № 252/32-III «Астана қаласының аумағында құрылыс салу Қағидалары туралы» шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/53300/rus
