act_code: '29026'
requisite: Решение Маслихата города Астаны от 7 июня 2006 года N 252/32-III. Зарегистрировано в Департаменте юстиции города Астаны от 27 июля 2006 года N 447. Утратило силу решением маслихата города Астаны от 3 марта 2011 года № 432/58-IV
title:
  rus: О Правилах застройки территории города Астаны
  kaz: Астана қаласының аумағында құрылыс салу Қағидалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-06-07
approved_by:
- '151000000002'
version_date:
  kaz: 2010-12-13
  rus: 2010-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/29026/kaz/13.12.2010
  rus: https://zan.gov.kz/client/#!/doc/29026/rus/13.12.2010
caused_by:
  code: '56547'
  requisite: Решение маслихата города Астаны от 13 декабря 2010 года № 413/54-IV. Зарегистрировано Департаментом юстиции города Астаны 31 декабря 2010 года № 661. Утратило силу решением маслихата города Астаны от 3 марта 2011 года № 432/58-IV
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 7 июня 2006 года № 252/32-III "О Правилах застройки территории города Астаны"
    kaz: Астана қаласы мәслихатының 2006 жылғы 7 маусымдағы № 252/32-III "Астана қаласының аумағында құрылыс салу қағидалары туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56547/rus
