act_code: '29026'
requisite: Решение Маслихата города Астаны от 7 июня 2006 года N 252/32-III. Зарегистрировано в Департаменте юстиции города Астаны от 27 июля 2006 года N 447. Утратило силу решением маслихата города Астаны от 3 марта 2011 года № 432/58-IV
title:
  rus: О Правилах застройки территории города Астаны
  kaz: Астана қаласының аумағында құрылыс салу Қағидалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-06-07
approved_by:
- '151000000002'
version_date:
  kaz: 2009-08-26
  rus: 2009-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/29026/kaz/26.08.2009
  rus: https://zan.gov.kz/client/#!/doc/29026/rus/26.08.2009
caused_by:
  code: '47992'
  requisite: Решение маслихата города Астаны от 26 августа 2009 года № 243/37-IV. Зарегистрировано Департаментом юстиции города Астаны 1 октября 2009 года № 590. Утратило силу решением маслихата города Астаны от 12 декабря 2017 года № 219/25-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в некоторые решения маслихата города Астаны
    kaz: Астана қаласы мәслихатының кейбір шешімдеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47992/rus
