act_code: '22401'
requisite: Решение маслихата города Астаны от 24 декабря 2004 года N 110/15-III. Зарегистрировано Департаментом юстиции города Астаны 29 декабря 2004 года N 368. Утратило силу - решением маслихата города Астаны от 23 декабря 2005 года N 212/28-III.
title:
  rus: Об установлении ставок платы за загрязнение окружающей среды по городу Астане на 2005 год
  kaz: Астана қаласы бойынша 2005 жылға қоршаған ортаны ластағаны үшін төлем ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-12-24
approved_by:
- '151000000002'
version_date:
  kaz: 2004-12-24
  rus: 2004-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/22401/kaz/24.12.2004
  rus: https://zan.gov.kz/client/#!/doc/22401/rus/24.12.2004
