act_code: '209080'
requisite: Решение акима города Астаны от 8 апреля 2025 года № 01-7. Зарегистрировано Департаментом юстиции города Астаны 11 апреля 2025 года № 1409-01
title:
  rus: Об образовании избирательных участков по городу Астане
  kaz: Астана қаласы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-04-08
approved_by:
- '151000000003'
version_date:
  kaz: 2025-04-08
  rus: 2025-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/209080/kaz/08.04.2025
  rus: https://zan.gov.kz/client/#!/doc/209080/rus/08.04.2025
