act_code: '41557'
requisite: Решение маслихата города Астаны от 9 июля 2008 года N 114/18-IV. Зарегистрировано Департаментом юстиции города Астаны 15 августа 2008 года N 540. Утратило силу решением маслихата города Астаны от 27 июня 2014 года № 250/36-V
title:
  rus: О Правилах оказания социальной помощи нуждающимся гражданам, больным активным туберкулезом
  kaz: Белсенді туберкулезбен ауыратын мұқтаж азаматтарға әлеуметтік көмек көрсету Қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2008-07-09
approved_by:
- '151000000002'
version_date:
  kaz: 2010-12-13
  rus: 2010-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/41557/kaz/13.12.2010
  rus: https://zan.gov.kz/client/#!/doc/41557/rus/13.12.2010
caused_by:
  code: '56989'
  requisite: Решение маслихата города Астаны от 13 декабря 2010 года № 411/54-IV. Зарегистрировано Департаментом юстиции города Астаны 12 января 2011 года № 665. Утратило силу решение маслихата города Астаны от 27 июня 2014 года № 250/36-V
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 9 июля 2008 года № 114/18-IV "О Правилах оказания социальной помощи нуждающимся гражданам, больным активным туберкулезом"
    kaz: Астана қаласы мәслихатының 2008 жылғы 9 шілдедегі № 114/18-ІV "Белсенді туберкулезбен ауыратын мұқтаж азаматтарға әлеуметтік көмек көрсету қағидасы туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56989/rus
