act_code: '120967'
requisite: Решение маслихата города Астаны от 29 марта 2018 года № 247/30-VI. Зарегистрировано Департаментом юстиции города Астаны 20 апреля 2018 года № 1170. Утратило силу решением маслихата города Нур-Султана от 25 мая 2022 года № 179/25-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат маслихата города Астаны»
  kaz: «Астана қаласы мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-03-29
approved_by:
- '151000000002'
version_date:
  kaz: 2018-03-29
  rus: 2018-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/120967/kaz/29.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120967/rus/29.03.2018
