act_code: '75867'
requisite: Решение маслихата города Астаны от 13 декабря 2013 года № 196/28-V. Зарегистрировано Департаментом юстиции города Астаны 13 декабря 2013 года № 794. Утратило силу решением маслихата города Астаны от 27 марта 2014 года № 226/31-V
title:
  rus: О Правилах оказания единовременной социальной помощи жертвам политических репрессий из числа участников событий 17-18 декабря 1986 года в Казахстане ко Дню Независимости Республики Казахстан
  kaz: Қазақстан Республикасының Тәуелсіздігі күніне орай Қазақстандағы 1986 жылғы 17-18 желтоқсан оқиғаларына қатысушылар қатарындағы саяси қуғын-сүргін құрбандарына біржолғы әлеуметтік көмек көрсету қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-12-13
approved_by:
- '151000000002'
version_date:
  kaz: 2013-12-13
  rus: 2013-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/75867/kaz/13.12.2013
  rus: https://zan.gov.kz/client/#!/doc/75867/rus/13.12.2013
