act_code: '40562'
requisite: Решение Маслихата города Астаны от 5 июня 2008 года № 109/16-IV. Зарегистрировано Департаментом юстиции города Астаны 30 июня 2008 года за № 537. Утратило силу решением маслихата города Астаны от 31 августа 2026 года № 456/58-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении описания и порядка использования символов столицы Республики Казахстан – города Астаны
  kaz: Қазақстан Республикасының елордасы – Астана қаласының рәміздерінің сипаттамасын және оларды пайдалану тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-05
approved_by:
- '151000000002'
version_date:
  kaz: 2008-06-05
  rus: 2008-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/40562/kaz/05.06.2008
  rus: https://zan.gov.kz/client/#!/doc/40562/rus/05.06.2008
