act_code: '223697'
requisite: Решение маслихата города Астаны от 19 марта 2026 года № 396/51-VIII
title:
  rus: Об утверждении минимального размера взносов на управление объектом кондоминиума в городе Астане на 2026 год
  kaz: Астана қаласында 2026 жылға арналған кондоминиум объектісін басқаруға арналған жарналардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-03-19
approved_by:
- '151000000002'
version_date:
  kaz: 2026-03-19
  rus: 2026-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/223697/kaz/19.03.2026
  rus: https://zan.gov.kz/client/#!/doc/223697/rus/19.03.2026
