act_code: '187873'
requisite: Решение маслихата города Астаны от 3 октября 2023 года № 87/10-VIII. Зарегистрировано Департаментом юстиции города Астаны 2 ноября 2023 года № 1362-01
title:
  rus: Об утверждении Правил создания, содержания и защиты зеленых насаждений на территории города Астаны
  kaz: Астана қаласының аумағындағы Жасыл екпелерді жасау, күтіп-ұстау және қорғау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-03
approved_by:
- '151000000002'
version_date:
  kaz: 2023-10-03
  rus: 2023-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/187873/kaz/03.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187873/rus/03.10.2023
