act_code: '187873'
requisite: Решение маслихата города Астаны от 3 октября 2023 года № 87/10-VIII. Зарегистрировано Департаментом юстиции города Астаны 2 ноября 2023 года № 1362-01
title:
  rus: Об утверждении Правил создания, содержания и защиты зеленых насаждений на территории города Астаны
  kaz: Астана қаласының аумағындағы Жасыл екпелерді жасау, күтіп-ұстау және қорғау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-03
approved_by:
- '151000000002'
version_date:
  kaz: 2024-08-27
  rus: 2024-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/187873/kaz/27.08.2024
  rus: https://zan.gov.kz/client/#!/doc/187873/rus/27.08.2024
caused_by:
  code: '200105'
  requisite: Решение маслихата города Астаны от 27 августа 2024 года № 213/26-VIII. Зарегистрировано Департаментом юстиции города Астаны 28 августа 2024 года № 1392-01
  title:
    rus: О внесении изменений и дополнения в решение маслихата города Астаны от 3 октября 2023 года № 87/10-VIII «Об утверждении Правил создания, содержания и защиты зеленых насаждений на территории города Астаны»
    kaz: «Астана қаласының аумағындағы Жасыл екпелерді жасау, күтіп-ұстау және қорғау қағидаларын бекіту туралы» Астана қаласы мәслихатының 2023 жылғы 3 қазандағы № 87/10-VIII шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200105/rus
