act_code: '64727'
requisite: Решение маслихата города Астаны от 28 марта 2012 года № 9/2-V. Зарегистрировано Департаментом юстиции города Астаны 18 апреля 2012 года № 720. Утратило силу решением маслихата города Астаны от 6 июня 2012 года № 35/4-V
title:
  rus: О Правилах оказания единовременной социальной помощи отдельным категориям нуждающихся граждан города Астаны к празднику Наурыз мейрамы
  kaz: Наурыз мейрамы мерекесіне Астана қаласындағы мұқтаж азаматтардың жекелеген санаттарына біржолғы әлеуметтiк көмек көрсету ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-03-28
approved_by:
- '151000000002'
version_date:
  kaz: 2012-03-28
  rus: 2012-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/64727/kaz/28.03.2012
  rus: https://zan.gov.kz/client/#!/doc/64727/rus/28.03.2012
