act_code: '44331'
requisite: Решение акимата города Астаны от 26 января 2009 года N 33-4. Зарегистрировано Департаментом юстиции города Астаны 16 февраля 2009 года N 561. Утратило силу решением акимата города Астаны от 1 декабря 2009 года N 33-18
title:
  rus: О проведении приписки граждан к призывным участкам районов "Алматы", "Сарыарка" и "Есиль" города Астаны в январе-марте 2009 года
  kaz: Астана қаласы "Алматы", "Сарыарқа" және "Есіл" аудандарының шақыру учаскелеріне 2009 жылдың қаңтар-наурыз айларында азаматтарды тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-26
approved_by:
- '151000000001'
version_date:
  kaz: 2009-01-26
  rus: 2009-01-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/44331/kaz/26.01.2009
  rus: https://zan.gov.kz/client/#!/doc/44331/rus/26.01.2009
