act_code: '191484'
requisite: Решение маслихата города Астаны от 14 декабря 2023 года № 113/15-VIII
title:
  rus: О бюджете города Астаны на 2024-2026 годы
  kaz: Астана қаласының 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-14
approved_by:
- '151000000002'
version_date:
  kaz: 2024-07-02
  rus: 2024-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/191484/kaz/02.07.2024
  rus: https://zan.gov.kz/client/#!/doc/191484/rus/02.07.2024
caused_by:
  code: '198725'
  requisite: Решение маслихата города Астаны от 2 июля 2024 года № 206/25-VIII
  title:
    rus: О внесении изменения в решение маслихата города Астаны от 14 декабря 2023 года № 113/15-VIII «О бюджете города Астаны на 2024-2026 годы»
    kaz: «Астана қаласының 2024-2026 жылдарға арналған бюджеті туралы» Астана қаласы мәслихатының 2023 жылғы 14 желтоқсандағы № 113/15-VIII шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198725/rus
