act_code: '59383'
requisite: Решение маслихата города Астаны от 29 июня 2011 года № 464/65-IV. Зарегистрировано Департаментом юстиции города Астаны 29 июня 2011 года № 683. Утратило силу решением маслихата города Астаны от 7 декабря 2011 года № 530/75-IV
title:
  rus: О переносе дней отдыха
  kaz: Демалыс күндерін ауыстыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-06-29
approved_by:
- '151000000002'
version_date:
  kaz: 2011-06-29
  rus: 2011-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/59383/kaz/29.06.2011
  rus: https://zan.gov.kz/client/#!/doc/59383/rus/29.06.2011
