act_code: '137848'
requisite: Решение маслихата города Нур-Султана от 12 декабря 2019 года № 461/58-VI. Зарегистрировано Департаментом юстиции города Нур-Султана 31 декабря 2019 года № 1257
title:
  rus: Об установлении границ санитарных зон содержания животных на территории города Нур-Султан
  kaz: Нұр-Сұлтан қаласының аумағында жануарларды асыраудың санитариялық аймақтарының шекараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-12
approved_by:
- '150000000002'
version_date:
  kaz: 2019-12-12
  rus: 2019-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/137848/kaz/12.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137848/rus/12.12.2019
