act_code: '11101'
requisite: Решение Маслихата города Астаны от 25 декабря 2001 года N 124/26-II Зарегистрировано управлением юстиции г.Астаны от 29 января 2002 года N 164. Утратило силу решением маслихата города Астаны от 29 января 2009 года N 184/30-IV
title:
  rus: О схеме зонирования земель города Астаны
  kaz: Астана қаласындағы жерлердi аймақтарға бөлудiң кестесi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-25
approved_by:
- '151000000002'
version_date:
  kaz: 2001-12-25
  rus: 2001-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/11101/kaz/25.12.2001
  rus: https://zan.gov.kz/client/#!/doc/11101/rus/25.12.2001
