act_code: '23778'
requisite: "Решение Маслихата города Астаны от 29 марта 2005 года N 127/17-III.\r\nЗарегистрировано Департаментом юстиции города Астаны 29 апреля 2005 года N 387. Утратило силу решением маслихата города Астаны от 11 марта 2011 года N 441/59-IV"
title:
  rus: О Правилах оплаты стоимости проезда больных, направляемых по медицинским показаниям на лечение в пределах Республики Казахстан
  kaz: Дәрігерлік көрсеткіштер бойынша Қазақстан Республикасы шегінде емделуге жіберілетін науқастардың жол жүру құнын өтеу Қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-03-29
approved_by:
- '151000000002'
version_date:
  kaz: 2009-08-26
  rus: 2009-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/23778/kaz/26.08.2009
  rus: https://zan.gov.kz/client/#!/doc/23778/rus/26.08.2009
caused_by:
  code: '47992'
  requisite: Решение маслихата города Астаны от 26 августа 2009 года № 243/37-IV. Зарегистрировано Департаментом юстиции города Астаны 1 октября 2009 года № 590. Утратило силу решением маслихата города Астаны от 12 декабря 2017 года № 219/25-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в некоторые решения маслихата города Астаны
    kaz: Астана қаласы мәслихатының кейбір шешімдеріне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47992/rus
