act_code: '55862'
requisite: Решение маслихата города Астаны от 26 ноября 2010 года № 404/53-IV. Зарегистрировано Департаментом юстиции города Астаны 13 декабря 2010 года № 658. Утратило силу решением маслихата города Нур-Султана от 17 августа 2022 года № 218/28-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении границ охранных зон, зон регулирования застройки памятников истории и культуры города Астаны
  kaz: Астана қаласының тарихи және мәдени ескерткіштерін қорғау аймақтарының, құрылыс салуды реттеу аймақтарының шекараларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-26
approved_by:
- '151000000002'
version_date:
  kaz: 2010-11-25
  rus: 2010-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/55862/kaz/25.11.2010
  rus: https://zan.gov.kz/client/#!/doc/55862/rus/25.11.2010
