act_code: '22810'
requisite: Решение Маслихата города Астаны от 24 декабря 2004 года N 108/15-III. Зарегистрировано Департаментом юстиции Республики Казахстан 2 февраля 2005 года N 376. Утратило силу решением маслихата города Астаны от 12 декабря 2007 года N 27/6-IV
title:
  rus: О Программе развития системы образования города Астаны на 2005-2007 годы
  kaz: '"Астана қаласының бiлiм беру жүйесiн дамытудың 2005-2007 жылдарға арналған Бағдарламасы" туралы'
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2004-12-24
approved_by:
- '151000000002'
version_date:
  kaz: 2004-12-24
  rus: 2004-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/22810/kaz/24.12.2004
  rus: https://zan.gov.kz/client/#!/doc/22810/rus/24.12.2004
