act_code: '31265'
requisite: Решение маслихата города Астаны от 14 декабря 2006 года № 304/40-III. Зарегистрировано Департаментом юстиции города Астаны от 16 января 2007 года № 455. Утратило силу решением маслихата города Астаны от 27 мая 2008 года № 94/15/IV
title:
  rus: О бюджете города Астаны на 2007 год
  kaz: Астана қаласының 2007 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-14
approved_by:
- '151000000002'
version_date:
  kaz: 2007-02-09
  rus: 2007-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/31265/kaz/09.02.2007
  rus: https://zan.gov.kz/client/#!/doc/31265/rus/09.02.2007
caused_by:
  code: '32280'
  requisite: Решение Маслихата города Астаны от 9 февраля 2007 года N 340/43-III. Зарегистрированно Департаментом юстиции города Астаны 27 февраля 2007 года N 462. Утратило силу решением маслихата города Астаны от 27 мая 2008 года N 94/15/IV
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 14 декабря 2006 года N 304/40-III "О бюджете города Астаны на 2007 год"»
    kaz: '"Астана қаласының 2007 жылға арналған бюджеті туралы" Астана қаласы мәслихатының 2006 жылғы 14 желтоқсандағы 304/40-ІІІ шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/32280/rus
