act_code: '26392'
requisite: Решение Маслихата города Астаны от 6 декабря 2005 года N 207/25-III. Зарегистрировано в Департаменте юстиции г. Астаны 14 января 2006 года за N 426. В связи с истечением срока действия утратило силу - письмом Маслихата города Астаны от 19 февраля 2007 года N 88-03-12
title:
  rus: О бюджете города Астаны на 2006 год
  kaz: Астана қаласының 2006 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-06
approved_by:
- '151000000002'
version_date:
  kaz: 2006-02-08
  rus: 2006-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/26392/kaz/08.02.2006
  rus: https://zan.gov.kz/client/#!/doc/26392/rus/08.02.2006
caused_by:
  code: '26694'
  requisite: Решение маслихата города Астаны от 8 февраля 2006 года N 225/29-III. Зарегистрировано в Департаменте юстиции города Астаны от 2 марта 2006 года за N 434. В связи с истечением срока действия утратило силу - письмом Маслихата города Астаны от 19 февраля 2007 года N 88-03-12
  title:
    rus: О внесении изменений в решение маслихата города Астаны от 6 декабря 2005 года N 207/25-III "О бюджете города Астаны на 2006 год"
    kaz: Астана қаласы мәслихатының 2005 жылғы 6 желтоқсандағы 207/25-ІІІ "Астана қаласының 2006 жылға арналған бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/26694/rus
