act_code: '26392'
requisite: Решение Маслихата города Астаны от 6 декабря 2005 года N 207/25-III. Зарегистрировано в Департаменте юстиции г. Астаны 14 января 2006 года за N 426. В связи с истечением срока действия утратило силу - письмом Маслихата города Астаны от 19 февраля 2007 года N 88-03-12
title:
  rus: О бюджете города Астаны на 2006 год
  kaz: Астана қаласының 2006 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-06
approved_by:
- '151000000002'
version_date:
  kaz: 2005-12-06
  rus: 2005-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/26392/kaz/06.12.2005
  rus: https://zan.gov.kz/client/#!/doc/26392/rus/06.12.2005
