act_code: '16471'
requisite: Решение Маслихата города Астаны от 4 июля 2003 года N 245/47-II. Зарегистрировано Управлением юстиции города Астаны 29 июля 2003 года N 282. Утратило силу - решением Маслихата города Астаны от 21 сентября 2006 года N 285/35-III
title:
  rus: О Программе по снижению бедности в городе Астане на 2003-2005 годы
  kaz: Астана қаласында кедейшiлiктi азайту жөнiндегi 2003-2005 жылдарға арналған бағдарлама туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2003-07-03
approved_by:
- '151000000002'
version_date:
  kaz: 2003-07-03
  rus: 2003-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/16471/kaz/03.07.2003
  rus: https://zan.gov.kz/client/#!/doc/16471/rus/03.07.2003
