act_code: '85703'
requisite: Постановление акимата города Астаны от 2 декабря 2014 года № 111-22. Зарегистрировано Департаментом юстиции города Астаны 9 января 2015 года № 872. Утратило силу решением акима города Астаны от 4 октября 2024 года № 502-18 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил реализации продукции в стеклянной таре в местах проведения спортивно-массовых, зрелищных культурно-массовых мероприятий в городе Астане
  kaz: Астана қаласында спорттық-бұқаралық, ойын-сауық, мәдени-бұқаралық іс-шаралар өткізілетін орындарда шыны ыдыстағы өнімдерді сату қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-02
approved_by:
- '151000000001'
version_date:
  kaz: 2014-12-02
  rus: 2014-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/85703/kaz/02.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85703/rus/02.12.2014
