act_code: '175800'
requisite: Решение маслихата города Астаны от 14 декабря 2022 года № 280/36-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 декабря 2022 года № 31187. Утратило силу решением маслихата города Астаны от 31 октября 2023 года № 95/12-VIII
title:
  rus: Об утверждении ставок туристского взноса для иностранцев в городе Астане на 2023 год
  kaz: Астана қаласындағы шетелдіктер үшін 2023 жылға арналған туристік жарнаның мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-14
approved_by:
- '151000000002'
version_date:
  kaz: 2022-12-14
  rus: 2022-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/175800/kaz/14.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175800/rus/14.12.2022
