act_code: '21827'
requisite: Решение Маслихата города Астаны от 30 сентября 2004 года N 80/12-III. Зарегистрировано Департаментом юстиции города Астаны 11 ноября 2004 года N 360. Утратило силу решением маслихата города Астаны от 12 июля 2007 года N 408/50-III
title:
  rus: О Правилах санитарно-технического содержания объектов производства, социального, бытового обслуживания населения, а также объектов жилищного фонда города Астаны
  kaz: Астана қаласының өндіріс, халыққа әлеуметтік, тұрмыстық қызмет көрсету объектілерін, сондай-ақ тұрғын үй қоры объектілерін санитарлық-техникалық күтіп ұстау ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-09-29
approved_by:
- '151000000002'
version_date:
  kaz: 2004-09-29
  rus: 2004-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/21827/kaz/29.09.2004
  rus: https://zan.gov.kz/client/#!/doc/21827/rus/29.09.2004
