act_code: '127991'
requisite: Решение маслихата города Астаны от 9 ноября 2018 года № 326/41-VI. Зарегистрировано Департаментом юстиции города Астаны 29 декабря 2018 года № 1197
title:
  rus: О схеме зонирования земель для целей налогообложения и процентах повышения (понижения) базовых ставок земельного налога
  kaz: Салық салу мақсатында жерді аймаққа бөлу схемасы және жер салығының базалық мөлшерлемелерін арттыру (азайту) пайыздары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-09
approved_by:
- '151000000002'
version_date:
  kaz: 2018-11-09
  rus: 2018-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/127991/kaz/09.11.2018
  rus: https://zan.gov.kz/client/#!/doc/127991/rus/09.11.2018
