act_code: '194541'
requisite: Решение маслихата города Астаны от 7 марта 2024 года № 150/19-VIII. Зарегистрировано Департаментом юстиции города Астаны 18 марта 2024 года № 1372-01
title:
  rus: Об оказании дополнительной социальной помощи отдельным категориям нуждающихся граждан города Астаны к 35-летию вывода ограниченного контингента советских войск из Демократической Республики Афганистан
  kaz: Астана қаласы мұқтаж азаматтарының жекелеген санаттарына кеңес әскерлерінің шектеулі контингентін Ауғанстан Демократиялық Республикасынан шығаруының 35 жылдығына орай қосымша әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-07
approved_by:
- '151000000002'
version_date:
  kaz: 2024-03-07
  rus: 2024-03-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/194541/kaz/07.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194541/rus/07.03.2024
