act_code: '187975'
requisite: Решение маслихата города Астаны от 31 октября 2023 года № 95/12-VIII. Зарегистрировано Департаментом юстиции города Астаны 6 ноября 2023 года № 1363-01
title:
  rus: Об утверждении ставок туристского взноса для иностранцев в городе Астане
  kaz: Астана қаласында шетелдіктер үшін туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-31
approved_by:
- '151000000002'
version_date:
  kaz: 2023-10-31
  rus: 2023-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/187975/kaz/31.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187975/rus/31.10.2023
